apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  source:
    chart: sonarr
    repoURL: https://media-servarr.shw.al/charts
    targetRevision: 0.9.0
    helm:
      releaseName: media
      values: |
        application:
          config: null
        deployment:
          container:
            image:
              repository: "ghcr.io/linuxserver/sonarr"
              tag: "4.0.16"
              pullPolicy: IfNotPresent

            volumeMounts:
              - name: downloads
                mountPath: '/data'

          volumes:
            config:
              persistentVolumeClaim:
                claimName: "sonarr-config"
            downloads:
              persistentVolumeClaim:
                claimName: "media-qbittorrent-downloads"

        persistentVolumeClaims:
          sonarr-config:
            accessMode: 'ReadWriteOnce'
            requestStorage: '1Gi'
            selector: {}

        metrics:
          enabled: false
        ingress:
          enabled: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: media

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
