apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr-test
  namespace: argocd
spec:
  project: default
  source:
    chart: sonarr
    repoURL: https://panzer1119.github.io/helm-charts
    targetRevision: 0.1.8
    helm:
      releaseName: panzer1119
      valuesObject:
        image:
          tag: "4.0.16"
          pullPolicy: IfNotPresent

        env:
          TZ: "Europe/Paris"

        persistence:
          enabled: true
          storageClass: "longhorn"
          accessMode: ReadWriteOnce
          size: 10Gi

  destination:
    server: "https://kubernetes.default.svc"
    namespace: media

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
