apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr-test
  namespace: argocd
spec:
  project: default
  source:
    chart: sonarr
    repoURL: https://charts.pree.dev
    targetRevision: 1.11.1
    helm:
      releaseName: pree
      valuesObject:
        image:
          repository: linuxserver/sonarr
          tag: "4.0.16"
          pullPolicy: IfNotPresent

        env:
          TZ: "Europe/Paris"

        metrics:
          enabled: false

        persistence:
          config:
            enabled: true
            accessMode: ReadWriteOnce
            storageClassName: "longhorn"
            size: 1Gi
          downloads:
            enabled: true
            mountPath: /data
            existingClaim: gabe565-qbittorrent-downloads

        probes:
          liveness:
            enabled: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: media

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
