apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr-test
  namespace: argocd
spec:
  project: default
  source:
    chart: sonarr
    repoURL: https://media-servarr.shw.al/charts
    targetRevision: 0.9.0
    helm:
      releaseName: toto
      valuesObject:
        application:
          config: null
        deployment:
          container:
            volumeMounts:
              - name: downloads
                mountPath: '/data'

          volumes:
            config:
              persistentVolumeClaim:
                claimName: "sonarr-config-test"
            downloads:
              persistentVolumeClaim:
                claimName: "gabe565-qbittorrent-downloads"

        persistentVolumeClaims:
          sonarr-config: null
          sonarr-config-test:
            accessMode: 'ReadWriteOnce'
            requestStorage: '1Gi'
            selector: {}

        metrics:
          enabled: false
        ingress:
          enabled: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: media

  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
