apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  source:
    chart: sonarr
    repoURL: https://media-servarr.shw.al/charts
    targetRevision: 0.9.0
    helm:
      releaseName: media
      values: |
        application:
          config:
            contents: |
              <Config>
                <BindAddress>*</BindAddress>
                <Port>8989</Port>
                <SslPort>9898</SslPort>
                <EnableSsl>False</EnableSsl>
                <LaunchBrowser>True</LaunchBrowser>
                <ApiKey>$apikey</ApiKey>
                <AuthenticationMethod>Forms</AuthenticationMethod>
                <AuthenticationRequired>Enabled</AuthenticationRequired>
                <Branch>main</Branch>
                <LogLevel>debug</LogLevel>
                <SslCertPath></SslCertPath>
                <SslCertPassword></SslCertPassword>
                <UrlBase></UrlBase>
                <InstanceName>Sonarr</InstanceName>
                <UpdateMechanism>Docker</UpdateMechanism>
                <AnalyticsEnabled>False</AnalyticsEnabled>
                <Theme>dark</Theme>
              </Config>
        deployment:
          container:
            volumeMounts:
              - name: downloads
                mountPath: '/data'

          volumes:
            config:
              persistentVolumeClaim:
                claimName: "sonarr-config"
            downloads:
              persistentVolumeClaim:
                claimName: "gabe565-qbittorrent-downloads"

        persistentVolumeClaims:
          sonarr-config: null
          sonarr-config:
            accessMode: 'ReadWriteOnce'
            requestStorage: '1Gi'
            selector: {}

        metrics:
          enabled: false
        ingress:
          enabled: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: media

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
