apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr-test
  namespace: argocd
spec:
  project: default
  source:
    chart: sonarr
    repoURL: https://media-servarr.shw.al/charts
    targetRevision: 0.9.0
    helm:
      releaseName: mediar-servarr
      valuesObject:
        application:
          config: null
        deployment:
          container:
            volumeMounts:
              - name: config-test
                mountPath: '/config'
              - name: downloads
                mountPath: '/data'

          volumes:
            config-test:
              persistentVolumeClaim:
                claimName: "toto"
            downloads:
              persistentVolumeClaim:
                claimName: "gabe565-qbittorrent-downloads"

        persistentVolumeClaim:
          toto:
            accessMode: ReadWriteOnce
            requestStorage: 1Gi

        metrics:
          enabled: false
        ingress:
          enabled: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: media

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
