apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr-test
  namespace: argocd
spec:
  project: default
  source:
    chart: sonarr
    repoURL: https://media-servarr.shw.al/charts
    targetRevision: 0.9.0
    helm:
      releaseName: toto
      valueFiles:
        - ../../values/sonarr.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: media

  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
