apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      krr-enforcer:rbac.authorization.k8s.io/ClusterRole:krr/krr-enforcer-simple-krr-dashboard
  labels:
    app.kubernetes.io/instance: krr-enforcer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: simple-krr-dashboard
    app.kubernetes.io/version: 1.1.0
    helm.sh/chart: simple-krr-dashboard-1.3.0
  name: krr-enforcer-simple-krr-dashboard
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
