apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-krr-dashboard
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
- apiGroups:
  - v1
  resources:
  - services
  verbs:
  - get
  - list
