apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vpa
    repo: https://charts.fairwinds.com/stable
    version: 4.11.0
    releaseName: vpa
    namespace: vpa
    includeCRDs: true
    valuesInline:
      admissionController:
        enabled: true
      updater:
        enabled: true
      recommender:
        enabled: true
