creation_rules:
  # Talos configuration files (local dev use only)
  - path_regex: talos/.*
    age: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
  # ArgoCD secrets
  - path_regex: argocd/.*secret.*\.yaml$
    age: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
