version: '3'

includes:
  terragrunt: ./tasks/terragrunt/Taskfile.yaml
  argocd: ./tasks/argocd/Taskfile.yaml

tasks:
  default:
    desc: Show available tasks
    silent: true
    cmd: task --list-all
