version: '3'

includes:
  tg: ./tasks/terragrunt/Taskfile.yaml
  argocd: ./tasks/argocd/Taskfile.yaml

tasks:
  default:
    desc: Show available tasks
    silent: true
    cmds:
      - |
        echo ""
        echo "  Homelab Infrastructure"
        echo "  ======================"
        echo ""
        echo "  Quick Start:"
        echo "    1. cp .env.example .env     # Configure credentials"
        echo "    2. task argocd:generate-secrets"
        echo "    3. task tg -- apply terraform/live/etcdme-nbg1-dc3"
        echo "    4. task argocd:bootstrap"
        echo ""
        echo "  Secrets:"
        echo "    argocd:generate-secrets   Generate and encrypt secrets"
        echo ""
        echo "  ArgoCD:"
        echo "    argocd:bootstrap          Deploy ArgoCD + applications"
        echo "    argocd:password           Get admin password"
        echo ""
        echo "  Terragrunt Stack:"
        echo "    tg -- generate <path>     Generate stack units"
        echo "    tg -- plan <path>         Plan all units"
        echo "    tg -- apply <path>        Apply all units"
        echo "    tg:bootstrap              Initialize S3 backend"
        echo "    tg:clean                  Clear cache"
        echo ""
