#ENC[AES256_GCM,data:Rw1enBs9CHs5gsBgauqkK5xLe3uQ8/KHyY5D1OCkTmU=,iv:InE+6LrQQZVmiqsTTrvziwfySl5YhtmWHaCSKVasLLQ=,tag:7/ZL31lSaOc4W4FqIeWT3w==,type:comment]
#
#ENC[AES256_GCM,data:xx4gGnsw/g==,iv:7SOSYATr7pkPhQq6br5fi7sro14DPv/39pym8rTuHL8=,tag:hHb/8K33J2hkXIOBNf9/rg==,type:comment]
#ENC[AES256_GCM,data:hiqz8X8paaWMMAG5uROKjNdAhv0cIM41K457OiF3cBe6yeUNuSfs,iv:wUK+femhnK8PwrO+Tzxpe6VM5kQMFnt5ic7ikHv5DDY=,tag:BxFKOK/Je/0KeYe9GUOMPg==,type:comment]
#ENC[AES256_GCM,data:UJSFepLXo6K9zHFtMWG+cZuq7lUu9FNyntC6jYrdnw7NrQ==,iv:L5noLkYE1Ha0aMVFd/chNq/oMC5Hym7j2fun9bd2p/o=,tag:XaKILL1rP6mp69GQ3RY4IA==,type:comment]
#
#ENC[AES256_GCM,data:segCgbbxWVaf8CDTfft9pjho+lftyPYSsbEUWjQjN406p7co1zjxvcPewtrvvi7uU7C0c3tPk+r35QLIEH33Uqn4NYij36r0,iv:z8Xw5Pcu5nbgIxgXzlNEchTRw4Rk+FL/MKgSr89oy4o=,tag:cxrrZVmzdEggLxOFXgWuHw==,type:comment]
#ENC[AES256_GCM,data:QvdmFi+mgmXPqqpJyLV91bdnkjJP9twIeM/8stSrFhgXdT/vPw==,iv:hJ1pcaCQZGNOTsK4UiLY9J1OVJMC5o7WHf4Az4+G7Q8=,tag:qKWg7T/2jdm2QN9oVNYk3g==,type:comment]
#ENC[AES256_GCM,data:dk2CjL6sAsK36tSCsp+VUnZccaCztA==,iv:1iddnLodb8HytGR40QKLX5ZOVdA19Vtafl5wCt1UCxY=,tag:ateWz5Q0ulIDVqJ0p349qg==,type:comment]
#ENC[AES256_GCM,data:5AY7offy+Qq/RoUjqLznlkY=,iv:otgqPJJ+1/QiXOvAOI4uX9yigBvktX3NyI/58P9hNgI=,tag:VL9KYY/d/CbKh8045FwwUw==,type:comment]
#ENC[AES256_GCM,data:u+KSba7doQJAv/tp06silK6hhQrMGmu05a56ZjwzR2+MbJ8=,iv:8tOes1z2Lv/iuEnG1c+5l+fsyaS9jxLByK8PdYSlAI0=,tag:gw6048QoQzo6Yw/vEaYFrg==,type:comment]
#ENC[AES256_GCM,data:F5270mtKsIfaiiYj7xWgk9BGBkCD/XOV4m3pEOtRO1fxRXdnpEAvEhFcnNSdA3lQN/xx/l4=,iv:mluhNEZCF+3oO8fHEdPq2pw6CQc652pxwvlJ1JCDgV4=,tag:tmA5bkhsRvrBI9BTg11bTg==,type:comment]
apiVersion: ENC[AES256_GCM,data:56A=,iv:e+5Eo1ev8F6nKztAW/Fgw3JDdFlb2NpbuvPwrTbN99Y=,tag:Zxcu8GQ5kA90bRc0e5Vtvw==,type:str]
kind: ENC[AES256_GCM,data:x0lhrPHq,iv:NOTJCa0n5OAbailMS4PljQTcBtKFMMD3KuJvxggkxuo=,tag:jf3/QjEn0umUCzzokAI0uQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NX+2if7JPbSRJayOtwzlRPATjw==,iv:V3UK9MoA3DSsMFq+4Bs3aihmfcQxc1OlktXGgR+LPuc=,tag:CO0sHUDabeCQWl1fkIACsA==,type:str]
    namespace: ENC[AES256_GCM,data:wvkT9bP+gxGQwMkD,iv:hGDyyQF7saEE2qDfTo0FJdqyk7+4g3EEozD+9EUImsw=,tag:ktZZ8VTFfXAFdEXElbzn0w==,type:str]
type: ENC[AES256_GCM,data:wWqApZGy,iv:UloVWZz0zDKBRLH6TdU67D3JSgbQXdzbdHtcGFOOzY4=,tag:UkfJiPZ1qY9gmfPdfMLBIA==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:970dUeTauqP4KJPum04UA1tKO34=,iv:EkE2pofQJz+8pJcyPuSGzVqasFJ9g5q3XTUkXUvRcRg=,tag:i0ttR0kgAKdPeiB70NlAQw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:FySmF7kQ6+EJ7hXCArSb0nmAzuoEZR+/kp4NlYUmgTiTa8Kn6U8HvA==,iv:vEH8fWIlUeAv3AZzhzulnR6bGOfcT6g4F9pmiI7yeEs=,tag:QzBtsjcDP4tnkUMRZWzOow==,type:str]
    hosted-zone-id: ENC[AES256_GCM,data:SM8MegIcIKPbFOO/GZ8gmHCcqEI=,iv:rXxVV9VLObwcQCidUm7/auQxfpgW2ICsHLR1y2+LHuA=,tag:7YeqmAM5Ieow3aC+kzIziA==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ak9wYjZTU1lFbzd3QWw2
            ZytlRHI3OG9LeEtTRjBOK2s5L3hBTVN2cHlNCk5kK0dQSVFZUTdydTRkeVJxdkRO
            TU1hcVp5MU5XS05EWXlYYUVzQzJXWjgKLS0tIGdyMmt5djI1Wi9oQnhjVkFDWDdV
            Y25PT0lXT1RnTHRSRlpEL0xBNmw4NFEKDRIsSKFLppkdcxsvZ6ATE8WGHI8k95Ug
            X0IReMaOXcpwSO3dFRPaisZmax0WJp6/sZqARZ4KUKM4BERGbtr+rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T16:29:24Z"
    mac: ENC[AES256_GCM,data:b/1mIZtTgYNqIqfMp+0/iqyVrD0iNf8ID2R1fbPVQxXZtF3u8r9ldCXz6XRhqRJnnGuAh7HDrvqvDtQg2JBNxuk2Pn+oYdVEJ7LRqZawt82SgZJ0kJH6aDJmZTa4D4fKFZ8GQejrYnov/2iIXDNemTVrkzoQ5CSt2wFua8KzxQs=,iv:Vmuux5x03XllgIwr83nhomX3yVje8pwgKmlQXbh3xqg=,tag:Uco34sO1/9uKiN9Vnle6RA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:SgBKbBk7OE5JO+hk+i+aMx29OjCZCcRhLKf+kYmwmYd0J7uNpVgybBvwz3udPRhW,iv:flOGnqLSyG838fxtjAtu+VhLfcrJW9+XXDmRL0bT6cE=,tag:hJMNTjblI/uJ85mGbjT8Jg==,type:comment]
apiVersion: ENC[AES256_GCM,data:6AU=,iv:bU/E2u5WY89k3OEOUXjdnB22C4ZO5CLP4+GENgE4xKs=,tag:AycyatLoOYRmNVAg57kpBQ==,type:str]
kind: ENC[AES256_GCM,data:q+Eu322m,iv:+GluRCppIBQwEKlkpN+wL5xYkyN9MH7jnrM+9+RSfBY=,tag:tn3F45z+3Ktwvx4GdmocmA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pZgXzhp28B2IIFjlIA==,iv:amT6DPH3sxcMGQvHaaTpmfv26zo0fhwYm9CATRGJ9Fw=,tag:Jlvd95LTja2dkCeR3tEjwQ==,type:str]
    namespace: ENC[AES256_GCM,data:mOV/FDp7,iv:HUYuNAZloQUiIn7hTxIa6rIPPaAKHb/JEcAfzVko60Y=,tag:ACgI8QC6UQdFqpTZIaYHcg==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:CSgqUHDFC/HS1M7nYQ==,iv:uyAzXGm321jJsT21Zdm5KyoFp3gHuYVj3hcdjIrJ8/k=,tag:8SXqoMDm33in3G+w69gb+g==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:gLSH+aep,iv:DbWUIzj/N305KTboE/cPcev/pSj6D/1SmtOYor9GPb8=,tag:5+s8IUkpSexWGWJ+DxzSfA==,type:str]
type: ENC[AES256_GCM,data:BrdIY6K5,iv:aSD/8SVFDBj1wKtem8KBSJAXZlf5YmYAL9aPOkayJFY=,tag:l6AHDyt2bXDUwf/KzDRkig==,type:str]
stringData:
    server.secretkey: ENC[AES256_GCM,data:ZP6XmV101AVAb0SLGFCoSPbdjAkd/BrrYNuQecX47XXdi/UI9f/FveltmwA=,iv:oXVDLZW57DAkkJkZ4wPkPjgySFiKGX5zMu3JXTp0AIM=,tag:V1IUa4/zyXAADwtYnrAn0A==,type:str]
    admin.password: ENC[AES256_GCM,data:niaiPJW9xQaUdcItSmkHdOsF+adWDsgG+O1H7uh0sQ1KekKAdMCCssYT2Y63z1+ekcp5IVXzZXMZAmquZ2Gx+SufgOgWU/5sY5mYhSqUFVMy+aMfX5hUkwQfFQ/69wqU5HvEU21qDEbbxqtLKsJwZorHI90J659bgwB0Tjy0CePcYL9MCp5WhTFTd7RbKzUQnF5ZYMNwDv5Mej7cMhLZPoVETmfQdh8RSddWpw==,iv:z851YXNOvC7+yUX9n73pyegESBAi33cyOha4b0B72RM=,tag:wzZaAI3HYhF9TZsq8dby7g==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:SjGbDWakFIeyB9MnRIyk9P6N03I=,iv:lyalNrRv7RzD3bZ2Y0tDi4P4U8EjXotjlSeXaiT5Xxk=,tag:OfwFHYsXIVut3/cMa5Y6ng==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ak9wYjZTU1lFbzd3QWw2
            ZytlRHI3OG9LeEtTRjBOK2s5L3hBTVN2cHlNCk5kK0dQSVFZUTdydTRkeVJxdkRO
            TU1hcVp5MU5XS05EWXlYYUVzQzJXWjgKLS0tIGdyMmt5djI1Wi9oQnhjVkFDWDdV
            Y25PT0lXT1RnTHRSRlpEL0xBNmw4NFEKDRIsSKFLppkdcxsvZ6ATE8WGHI8k95Ug
            X0IReMaOXcpwSO3dFRPaisZmax0WJp6/sZqARZ4KUKM4BERGbtr+rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T16:29:24Z"
    mac: ENC[AES256_GCM,data:b/1mIZtTgYNqIqfMp+0/iqyVrD0iNf8ID2R1fbPVQxXZtF3u8r9ldCXz6XRhqRJnnGuAh7HDrvqvDtQg2JBNxuk2Pn+oYdVEJ7LRqZawt82SgZJ0kJH6aDJmZTa4D4fKFZ8GQejrYnov/2iIXDNemTVrkzoQ5CSt2wFua8KzxQs=,iv:Vmuux5x03XllgIwr83nhomX3yVje8pwgKmlQXbh3xqg=,tag:Uco34sO1/9uKiN9Vnle6RA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:edbUs/uNGKG5JM5MCK4qnQaRpBvXi8Wi+6rJbFVLBuHt5K7YtYsxJAyFhRxHzwk=,iv:CndLLOBiZa3u9TTvwRQjcX0zUh2Ivv0JSq8HKXW3vas=,tag:jCsJ58V/H3mPfwIN9X6E6w==,type:comment]
apiVersion: ENC[AES256_GCM,data:+ks=,iv:P3N2q8CNgrxN8+7FFWGeG+3uBwo+tl5+wghfmTq5pEM=,tag:jxtumNZUJ1oBKsIthNTswg==,type:str]
kind: ENC[AES256_GCM,data:e4RraWWq,iv:/aHbNgxUGz1Pg/Nr+In37I+UofBlpfxt78PwNQqoELE=,tag:mxJ1ZGtsWs6oSxt4B+HXJg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/1nKcxxBWS5yGfjM,iv:G3qh7Xs/XbaJCF6vSC+8+e0Oo6LSheuTnAAUtEm5nNw=,tag:pwFIY5jtExjOWKLj5S2Iuw==,type:str]
    namespace: ENC[AES256_GCM,data:eM3KE+4c,iv:oRksuSmlTc7jIIkNJndzVS1lJFaY3gc9flcuhIYH7tU=,tag:0BH2sWkqc6jvz0OUKTPS9Q==,type:str]
type: ENC[AES256_GCM,data:UBA/Q9iC,iv:5AVGv6uV9WHEIdmtzUnj2LlP2oGcMjCuj1H8yvef7ug=,tag:UhRmVfGXcgkODfTc/fOfmA==,type:str]
stringData:
    keys.txt: ENC[AES256_GCM,data:pZY5Jv7klz15y3H5Cx4pXPT5pwcOU+3SUW/J4k0VBqWLU0OrHsSHrSbr6LoSXdOLOCyvNdISYsa5WLAPvq7H9mJSOgbeZlenQFOn,iv:fhKsyWU2V8YcQboi1hbCQcFzxLC2LP25q53K+7FCV7s=,tag:qYq/DhiGTe0XCvOik6TFQw==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ak9wYjZTU1lFbzd3QWw2
            ZytlRHI3OG9LeEtTRjBOK2s5L3hBTVN2cHlNCk5kK0dQSVFZUTdydTRkeVJxdkRO
            TU1hcVp5MU5XS05EWXlYYUVzQzJXWjgKLS0tIGdyMmt5djI1Wi9oQnhjVkFDWDdV
            Y25PT0lXT1RnTHRSRlpEL0xBNmw4NFEKDRIsSKFLppkdcxsvZ6ATE8WGHI8k95Ug
            X0IReMaOXcpwSO3dFRPaisZmax0WJp6/sZqARZ4KUKM4BERGbtr+rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T16:29:24Z"
    mac: ENC[AES256_GCM,data:b/1mIZtTgYNqIqfMp+0/iqyVrD0iNf8ID2R1fbPVQxXZtF3u8r9ldCXz6XRhqRJnnGuAh7HDrvqvDtQg2JBNxuk2Pn+oYdVEJ7LRqZawt82SgZJ0kJH6aDJmZTa4D4fKFZ8GQejrYnov/2iIXDNemTVrkzoQ5CSt2wFua8KzxQs=,iv:Vmuux5x03XllgIwr83nhomX3yVje8pwgKmlQXbh3xqg=,tag:Uco34sO1/9uKiN9Vnle6RA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:ZOdvkxBkNmUMZ7MEwZd8H+O609ewRidf9kA5cnPCGRS8YQ/P9J+pCOvDD//SS/c=,iv:xkVuOE1325Nm9+9OxFkNY+Z1FzN+x+seG+ej8kNTH40=,tag:DPPqspxcF7WTrlsqCx14uA==,type:comment]
apiVersion: ENC[AES256_GCM,data:24g=,iv:yjfdPwxSZcgLcDv4iQO0az49Z4gTMi0LWMVAZ2wowbc=,tag:jTBpErKI80nw2Ruh1smOKw==,type:str]
kind: ENC[AES256_GCM,data:pyT9QeIj,iv:DI+DIIty5Sp6AsfBXR9NsUItKCkwOf+FwHaSfcg+mDY=,tag:8GnlbZcEUGB+OjdWdVvu6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/TG1f7lxT/dkIA==,iv:b03fae7bqdwdWojHnTMhys2lEbjISufkNsgZ24kVzA8=,tag:tklL9HJQ2f8+3MuP4xf50g==,type:str]
    namespace: ENC[AES256_GCM,data:958dlVw=,iv:0M+sjWgDDpzc/+sTNZHBmfnsViZRCEtc8l1rVlonS7g=,tag:HwJJS+pm/46lyRvG3gbYDg==,type:str]
type: ENC[AES256_GCM,data:WYRcRSO4,iv:jwWQR1rlCyF2G+E8IUwA+OuUn0hE8+xA4LQo3i3Wo2k=,tag:6KuQ/dPq7MUvck7br93q7g==,type:str]
stringData:
    plexserver.claimcode: ENC[AES256_GCM,data:RFDLCsGypodW6KsJTG/X7zh7eewmKZ+dgHc=,iv:vVlxmP/8FFoglfdkh9N9IHdrx0tzPTwbx/Skasposn8=,tag:dMIIHcO1JDwRqVjKRCOF3w==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ak9wYjZTU1lFbzd3QWw2
            ZytlRHI3OG9LeEtTRjBOK2s5L3hBTVN2cHlNCk5kK0dQSVFZUTdydTRkeVJxdkRO
            TU1hcVp5MU5XS05EWXlYYUVzQzJXWjgKLS0tIGdyMmt5djI1Wi9oQnhjVkFDWDdV
            Y25PT0lXT1RnTHRSRlpEL0xBNmw4NFEKDRIsSKFLppkdcxsvZ6ATE8WGHI8k95Ug
            X0IReMaOXcpwSO3dFRPaisZmax0WJp6/sZqARZ4KUKM4BERGbtr+rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T16:29:24Z"
    mac: ENC[AES256_GCM,data:b/1mIZtTgYNqIqfMp+0/iqyVrD0iNf8ID2R1fbPVQxXZtF3u8r9ldCXz6XRhqRJnnGuAh7HDrvqvDtQg2JBNxuk2Pn+oYdVEJ7LRqZawt82SgZJ0kJH6aDJmZTa4D4fKFZ8GQejrYnov/2iIXDNemTVrkzoQ5CSt2wFua8KzxQs=,iv:Vmuux5x03XllgIwr83nhomX3yVje8pwgKmlQXbh3xqg=,tag:Uco34sO1/9uKiN9Vnle6RA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
