#ENC[AES256_GCM,data:m16Q8teYBoK1J4ZkJGewdWaoLsmuoCWS9i0t4HTqc5M=,iv:5lYSJqbIeKX3H9FethLnqicet9nhZBSRAEZ4zf9hY1E=,tag:lC7tiwkf2y70rF5bOD/RRQ==,type:comment]
#
#ENC[AES256_GCM,data:xcYGTVJV+A==,iv:vTzfoOh33OCXILe3e9Agn88LXRpTP1ggDhuY0RwF/Zw=,tag:sXQvMiRBBizqXzeh1cU75g==,type:comment]
#ENC[AES256_GCM,data:zoazquaQ3i61il3Hv85y/81zFBer2npfP9SL4hDP7QVOgzp3ZkwM,iv:wEf1nlR8o72AYp5IeRdfivvY4EX73Thlvo8Ythc5w0Q=,tag:7geyABTS93VJJ1OZ2jzBlA==,type:comment]
#ENC[AES256_GCM,data:n/MeKWk6c+1iF0hjlD15Dat4+Uvyb5O5GoCxtLJS1OBCnA==,iv:Lc7jCXMLHXVxZitZrigu7g/VdcgupRGzEcHuPoB4CXE=,tag:vOEhcT0e5W4bKdQ65n8KnA==,type:comment]
#
#ENC[AES256_GCM,data:q8DD9Ld/AphKx6v7o6LFLfrQbyWs5XtjOCdbQR7sBE5eOUf2UjeuyMGGg5cpx68CvrN+aZ+uF1gWQbJCfG9k2HIMyRq3i+xJ,iv:EY7cyQ2bcNYogWR/OWD4Te/L1Uba+ZuEuDu7Ncm8WV0=,tag:z9i6k/HnsYnnxX1eYSu+cw==,type:comment]
#ENC[AES256_GCM,data:btXg7lNCMBOutEZYUiSY105/HKz2sSlm74dievsNwJAwYKMqug==,iv:GpoNKJFptbsVHZsVbfbS1w0fz9pFq5Wz6mPKTFwJFS0=,tag:3KFuubcm9RQ3X1b7G1vaGg==,type:comment]
#ENC[AES256_GCM,data:wBj095XuyEkzevAMHjPkmJ/WW/UyKA==,iv:nTdTnUug0rabx0G8Cix7yJo5PfgCsg6Y1TiJOFaVYAI=,tag:9ptDByXkV/vomjBQwpuZIw==,type:comment]
#ENC[AES256_GCM,data:yPkZ1FMD3cap3aU2wlB3Csw=,iv:4XSaOxSbV9S0pPHexi2FQxrn0bFWwcN0LLEu6lSV8oA=,tag:M5tnHl9O2UkuHm+Ei54C7w==,type:comment]
#ENC[AES256_GCM,data:BEYkIoG1tIOYjQoKqKYEi+SD/B8ZDWHMdUKKHlMVoM+zFgQ=,iv:rj6FwVKvth2M0yweVMjtrULR5h2Isbk7MO7SObQKNNo=,tag:ScvSPUFQnmzpHe5zK0zBcw==,type:comment]
#ENC[AES256_GCM,data:ouiGCsWu0iiiujEPE/ElIBKR2XbnQYTxPnaKnaWdBgaDGVEjPmwrsaE+fByAYWcXju3PCsg=,iv:c/pbRLKSTJFFEAkhhgVMzTZbqzFb8HOci8aQUqejVDM=,tag:mEDsnUx3HESGfbnUicYRFg==,type:comment]
apiVersion: ENC[AES256_GCM,data:MBA=,iv:9Nflp8PnWcuW8CM61HOOxpHaRKBdJI450G1n3J6B+Tg=,tag:IDhrhS5BQO4jePvySsE0rA==,type:str]
kind: ENC[AES256_GCM,data:cVo9Cmz1,iv:aOvcVkIYJZd/xC22gCi5W5o0pKYb2dpC2KJdEyB442I=,tag:y6QAw2uaY9Je9o9MS5v3jA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SfyiHGVzy9AbkUI7hky4wh0gXw==,iv:iShByVqxHxCC7wQFn60U2A+yfwTLUaV48BQxdlzv34k=,tag:WDPKDv6ZdhxcXsjfMYyjtw==,type:str]
    namespace: ENC[AES256_GCM,data:q0jIN75ZT4GSU6Mf,iv:x5pikhbDRA7FnNnTRYhIUPyqou6CQy7udpPwLv8RdUM=,tag:9nrk4+g0T7hQnAFBg807HA==,type:str]
type: ENC[AES256_GCM,data:TWipx4yR,iv:cNhj9tc3fwrXXO6L/z6eoULpbYlVujHU0iWbHhwx0qM=,tag:bqS77/2ENBazdfwA+yoFqw==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:yR5HkIHq4tIP0pBHTvHIXz/A4SY=,iv:owjMV8VDVwgkUZGyNASvwxhFMyoMY4NcJKCZ0NDIcIM=,tag:Z2YS36GvAskSmaytquk22g==,type:str]
    secret-access-key: ENC[AES256_GCM,data:l5DggNyJIhIOSiR+uAHk0TNGN37XTadie+CqSeBLRkSIyhsURm8rsw==,iv:NSXm1wpOujfdX34Ezgi5WQgrphmRnlLYi7Z1yPDR04E=,tag:fth4aWTDjT4AnMvyxgSjRw==,type:str]
    hosted-zone-id: ENC[AES256_GCM,data:06wyiW4CzO+Ch1klXA+xZVg2yt0=,iv:dyOPrcwQRO9ggNfnhZcXoDGqa+P22GH1kPxr6m8CS60=,tag:k+mCjip98587uN72EllYyQ==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0tKMkU2NWF5a1pLNW1v
            ZjV3dS9sb3pBWm1PajU2NjlwRER6UG5Mbkc0Ci82bjgrNWNwRkZzdWdzaDltNXpm
            RFNrRXlpdXhjSEFSR1QweXJ0aHFoWjgKLS0tIHFmb3h0aFprVmVqZWlKVmIvSjVs
            K3ZpckwyZDRlNVFHSjQydUc5MS9WdkkKmxhuDwuiT6Ny7OghPfRv5DnfTI+ZsXfH
            +E+QnxUS64LNUMfSejHaETwQkqKcGg1qt4lDIhCk5MaZdKRRoHR20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T16:48:15Z"
    mac: ENC[AES256_GCM,data:yJmm0aMKReA3Elnf2LjEp9AGWZ2zYTOtTv7hCnmK8kChlzqwZDwi8b7CbBQzx/tpybwOm+zahAd1gsOVoboQqoXd2gFFLzV/RyEgqrWdaQydxKiripUPbza28dV7tzdsXZne6m4ImO4rxH5duNJxz3aptboSGiA/yzZTA9Q3G6Q=,iv:HP30H6yeOQEK9X3G+uP+deFWEIYuueukhE+N/+kL1dM=,tag:dD3DvzMhTnHGBoxwnfS42A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:7eujyBX82MY4IoPyKIBDlouLQYro8SKIyTuU/mpj0J7UbPvvKKsP8mppQZs24zgD,iv:k00ikds5hXRXXI6wZtJXX8WJ90V4NIu2bkJ1zZB7JHw=,tag:et5YOoCEgJc7UKMc42lD5g==,type:comment]
apiVersion: ENC[AES256_GCM,data:XMA=,iv:q115qFPW4zSm/9IxvQ0M/UDSHqyXiK7DschsPdJIFVM=,tag:lGfQLC7tcgGu3AEUyaXbdQ==,type:str]
kind: ENC[AES256_GCM,data:L7jfDuIw,iv:DkTli2PKkxxl6jhGwIX9HtbeDNVmv/WxmdMD8lUtPqQ=,tag:Mz5BqXlnElNZytzec/nb0Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l2AuupNeK48wubEX8Q==,iv:SjKIOdJlkZ0XCaTBI2ZrsQPz8ZzrNmBaQmdTmWBubWk=,tag:sRm+shbCyGFFU3PVC6ZrMg==,type:str]
    namespace: ENC[AES256_GCM,data:8K9hISw/,iv:DBaug1VOgxPNE6/zJteSFrjcGNhiinTLMbAy14RJpbM=,tag:eADFLYq0+ILJaRX9I7J1oQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:n/u4gOGHBglHvFqQbw==,iv:GBuSsBHPMhOj+MZoweIJJlJFDbaYsGT6rvpohU8+HBE=,tag:6MEcpvn9MPfiXQwuxkBNhw==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:f5s5cims,iv:rvMXZGyD/4gE8gj0o0B8doyZegMcPFMoTUZc9t6uJ5c=,tag:gIxJI6uAJx6ZubYnMUByrg==,type:str]
type: ENC[AES256_GCM,data:bViJZca/,iv:XJFairAfjqne9gQeeALfGlTgQCCK/SW2yVPyiWE4TPQ=,tag:U/7B/1Mn/umAKTiiOax4Uw==,type:str]
stringData:
    server.secretkey: ENC[AES256_GCM,data:rb98z/kV1w9sfXQxyzQ7Tb/1hRm8J1Khxb+nMFAXgSrxZgIg2WLYmPCThpA=,iv:SVVYtjlg0GUvJMveTfkRyMdAPw+EZAoyOq/GPp2lQ3w=,tag:51pL3UaawrIko3ezNwSITw==,type:str]
    admin.password: ENC[AES256_GCM,data:j0pmHHSlokk+5tWvcIk0VR+g0r8Ja9l4qkXkraIq2LZkT3BLYg6vsepkvHHZEN8Q6nIGwJiPAvRCGY2mTSlzZpbpwDOHx/jVbC8xbf7RmEUEg5Rp6FY/JQ/xXOiU565+N87zxw0AFhD1UC3v8Fze8rwb7oUWylg0lIj/TM4YzTQFHzZhLtWh1SUBUzg1XmE6mqMzFoPsa9d9B1MVPdddu9gFulmQ8EkOjxjDcA==,iv:MkaR5Wh4INj+peWTuauRw5GdYhTeINNxHMkMssIXaZU=,tag:oJHp1n0ysL6rYqK8BJU90A==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:xgKEHr2OseeqgPpK0H9dUY55cGk=,iv:zMNd3GbYOfEPjli6dYsaUYqilwg+JoECJdjKqfXpDzo=,tag:ZoKOgNPgstmCqfrZAEnEuQ==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0tKMkU2NWF5a1pLNW1v
            ZjV3dS9sb3pBWm1PajU2NjlwRER6UG5Mbkc0Ci82bjgrNWNwRkZzdWdzaDltNXpm
            RFNrRXlpdXhjSEFSR1QweXJ0aHFoWjgKLS0tIHFmb3h0aFprVmVqZWlKVmIvSjVs
            K3ZpckwyZDRlNVFHSjQydUc5MS9WdkkKmxhuDwuiT6Ny7OghPfRv5DnfTI+ZsXfH
            +E+QnxUS64LNUMfSejHaETwQkqKcGg1qt4lDIhCk5MaZdKRRoHR20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T16:48:15Z"
    mac: ENC[AES256_GCM,data:yJmm0aMKReA3Elnf2LjEp9AGWZ2zYTOtTv7hCnmK8kChlzqwZDwi8b7CbBQzx/tpybwOm+zahAd1gsOVoboQqoXd2gFFLzV/RyEgqrWdaQydxKiripUPbza28dV7tzdsXZne6m4ImO4rxH5duNJxz3aptboSGiA/yzZTA9Q3G6Q=,iv:HP30H6yeOQEK9X3G+uP+deFWEIYuueukhE+N/+kL1dM=,tag:dD3DvzMhTnHGBoxwnfS42A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:0YS7csLmdj7r5y+TRrlrl2WP/LX2hw+pSJICYzeZ34+3ftGjh5298X02dJBRDDM=,iv:QyAvpm27c/3ozg66QaVa1n1rme/8gNMpAcmGSvOfkpo=,tag:fwee1Zg7O0k7/0XRZg0BUg==,type:comment]
apiVersion: ENC[AES256_GCM,data:Ieg=,iv:fYcYvztb56i6j+g9XT9nT5DiSJEmEzxSl0BSIGNmVfg=,tag:LdyeciuUUFlmZh66sxK7DQ==,type:str]
kind: ENC[AES256_GCM,data:C8JPYl/d,iv:QcJ/7kD1TQGNUIP8f6d4CxsyF6OcjpAM2az0Dne1ybY=,tag:HY3Gdin9AJTnxaJspVaPFQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VAvXInRcImdqUam5,iv:TN0JxdnHaLkCFfRwwJm91yq3sVoy98xEzpvChwoG3hQ=,tag:NDL3pCOinb+2m80Wi4YIhA==,type:str]
    namespace: ENC[AES256_GCM,data:PZkiLidx,iv:ccwGEsNDX57nKbjDroyxxEEkURGhRfYU0fALMcD2cX4=,tag:V9LQMCEx8og6R3xPwslodQ==,type:str]
type: ENC[AES256_GCM,data:25vmsy+C,iv:hPuHZ4z1cHtty1p6Q1MMH3fz/jrkkedBcBcymfWBhTo=,tag:JRfZ7vzSQtmAF/+NDed5Vg==,type:str]
stringData:
    keys.txt: ENC[AES256_GCM,data:YZJ1MY0i+D39a0BAkKNb0X8mXIRq8D+K4EDjiuhsmmkupqZ4P4iV8NvqoX7/V9PAvjg/acmUaUTqMABbFuiGwrIFttSKdLTfzj67,iv:rYYa88ig3pjvxr2uR6wDcYpGNFbeCLKtJFPYKVPLgvM=,tag:MZU6SkJkvz9TMbWO5Onb2g==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0tKMkU2NWF5a1pLNW1v
            ZjV3dS9sb3pBWm1PajU2NjlwRER6UG5Mbkc0Ci82bjgrNWNwRkZzdWdzaDltNXpm
            RFNrRXlpdXhjSEFSR1QweXJ0aHFoWjgKLS0tIHFmb3h0aFprVmVqZWlKVmIvSjVs
            K3ZpckwyZDRlNVFHSjQydUc5MS9WdkkKmxhuDwuiT6Ny7OghPfRv5DnfTI+ZsXfH
            +E+QnxUS64LNUMfSejHaETwQkqKcGg1qt4lDIhCk5MaZdKRRoHR20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T16:48:15Z"
    mac: ENC[AES256_GCM,data:yJmm0aMKReA3Elnf2LjEp9AGWZ2zYTOtTv7hCnmK8kChlzqwZDwi8b7CbBQzx/tpybwOm+zahAd1gsOVoboQqoXd2gFFLzV/RyEgqrWdaQydxKiripUPbza28dV7tzdsXZne6m4ImO4rxH5duNJxz3aptboSGiA/yzZTA9Q3G6Q=,iv:HP30H6yeOQEK9X3G+uP+deFWEIYuueukhE+N/+kL1dM=,tag:dD3DvzMhTnHGBoxwnfS42A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:+3AEsq3j6xkm2M+Sli06oA==,iv:5Ie4Y4+VWAJ42F/CsqQodM8dwekHYDsGyXY9nYEktAo=,tag:byuokqw5MxEovEnlTyR0mw==,type:comment]
apiVersion: ENC[AES256_GCM,data:Wr4=,iv:WM0x617WfjOW6NmGBeeE+a+9Mt6X37KUdldv9C+36KY=,tag:3NyftT0U1pH5RuFvRMjyTQ==,type:str]
kind: ENC[AES256_GCM,data:3iI75WBz,iv:rqZj6RaRXWTYeKBev/pqi/C16h1oj7WF3hvNQJ0JLGE=,tag:nvEeDJ1BbOD2oNcJ/Pm/iQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xBTCrWmmz/OEfg==,iv:gPm3VWQXrmgSp9d29x4pl+5G1Wjzf3svJEhhIS0rhBY=,tag:Au94go1w8KRFMUeuA7MNOA==,type:str]
    namespace: ENC[AES256_GCM,data:k9Wpif0=,iv:aJsgalFSuLFYwmGCZeUE77VlqqHSxFtsnhGEC5ZjulM=,tag:FzmltCzKrONR2ga4Ge0APg==,type:str]
type: ENC[AES256_GCM,data:/8Hrwn1N,iv:lnvPSRvW7O5pLT/ZstE5/rcQa6uJiafLwVRYpH/lTSU=,tag:rhpeHi63rv0uTDToodb1uw==,type:str]
stringData:
    plexserver.claimcode: ENC[AES256_GCM,data:Yo3e+FpTNw2C93whwMG6OIHMLrSWWDjjW44=,iv:KjHRGARvIQgBjF09GiLPjT7xkRr6+mgq3KSjHt2sLEk=,tag:yXXOjDLInaBOz/bfUcwJjw==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0tKMkU2NWF5a1pLNW1v
            ZjV3dS9sb3pBWm1PajU2NjlwRER6UG5Mbkc0Ci82bjgrNWNwRkZzdWdzaDltNXpm
            RFNrRXlpdXhjSEFSR1QweXJ0aHFoWjgKLS0tIHFmb3h0aFprVmVqZWlKVmIvSjVs
            K3ZpckwyZDRlNVFHSjQydUc5MS9WdkkKmxhuDwuiT6Ny7OghPfRv5DnfTI+ZsXfH
            +E+QnxUS64LNUMfSejHaETwQkqKcGg1qt4lDIhCk5MaZdKRRoHR20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T16:48:15Z"
    mac: ENC[AES256_GCM,data:yJmm0aMKReA3Elnf2LjEp9AGWZ2zYTOtTv7hCnmK8kChlzqwZDwi8b7CbBQzx/tpybwOm+zahAd1gsOVoboQqoXd2gFFLzV/RyEgqrWdaQydxKiripUPbza28dV7tzdsXZne6m4ImO4rxH5duNJxz3aptboSGiA/yzZTA9Q3G6Q=,iv:HP30H6yeOQEK9X3G+uP+deFWEIYuueukhE+N/+kL1dM=,tag:dD3DvzMhTnHGBoxwnfS42A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:a/iOXdQx2RUbefKHvyqHNQ==,iv:Tz8PsKj5euSi5nJ96PoJ7G59YqREsnyCDtwu9L5iwUI=,tag:43wAa+EQ1zHQd8EBgMV1+g==,type:comment]
apiVersion: ENC[AES256_GCM,data:5Zk=,iv:HqLT4EkYdF6eUmaRJMHjISlYvsnvzYASsYnblrWLjPQ=,tag:YUOTNUmYdffqG0XC63hgMw==,type:str]
kind: ENC[AES256_GCM,data:1zM0Sy+K,iv:dBamhPKut47E+fCAuk61v9isgx3COSpmjxzOyPLD+bI=,tag:nLAv1U/vOF4158hUmWEStg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9Ili+KQqYhYpI2UOyhRkYF1Rbf0E,iv:+1MTZl4eon7gGoWfStR+9rHvppC0tITdnqQIfzueYMo=,tag:IOGMcHa9YbvImIirwRaFWw==,type:str]
    namespace: ENC[AES256_GCM,data:UMshHWKvf1gFOg==,iv:WI10bgKlWvuhb5eiCsE42Nc/OU8Z0bBROBUqWCzUkUA=,tag:NJKOv2HhjXKUbBjmXz+zTA==,type:str]
type: ENC[AES256_GCM,data:vmfUs1Co,iv:xtwea9BWiVZjEhqhKw55d438bh3iTjR2tInrqRX/NRg=,tag:ye4MCwKecOHM9gNihKlf1Q==,type:str]
stringData:
    bot-token: ENC[AES256_GCM,data:svx8jPb8lPoVaVXKO1pTWSBvMrxXq06bwOCgwuBFe4bcf4rnfb0jMiRcfY16iA==,iv:6k5utemag20kwVWfMhmxHFlTDbkh3rQC4hBGXky9TjY=,tag:vrwjyPMRdCX/JKQFpLiprw==,type:str]
    chat-id: ENC[AES256_GCM,data:KErVp+Xc7sQirg==,iv:0Wfd1j7v/4SYF87f3D2wchy9NC4PscY8FgTkBeChD8A=,tag:03TgXY7qkmFVKszGEVMMHA==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0tKMkU2NWF5a1pLNW1v
            ZjV3dS9sb3pBWm1PajU2NjlwRER6UG5Mbkc0Ci82bjgrNWNwRkZzdWdzaDltNXpm
            RFNrRXlpdXhjSEFSR1QweXJ0aHFoWjgKLS0tIHFmb3h0aFprVmVqZWlKVmIvSjVs
            K3ZpckwyZDRlNVFHSjQydUc5MS9WdkkKmxhuDwuiT6Ny7OghPfRv5DnfTI+ZsXfH
            +E+QnxUS64LNUMfSejHaETwQkqKcGg1qt4lDIhCk5MaZdKRRoHR20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T16:48:15Z"
    mac: ENC[AES256_GCM,data:yJmm0aMKReA3Elnf2LjEp9AGWZ2zYTOtTv7hCnmK8kChlzqwZDwi8b7CbBQzx/tpybwOm+zahAd1gsOVoboQqoXd2gFFLzV/RyEgqrWdaQydxKiripUPbza28dV7tzdsXZne6m4ImO4rxH5duNJxz3aptboSGiA/yzZTA9Q3G6Q=,iv:HP30H6yeOQEK9X3G+uP+deFWEIYuueukhE+N/+kL1dM=,tag:dD3DvzMhTnHGBoxwnfS42A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:MAWwY3wlOTN8b7cUjibmve9dUv5xsk0GorUc3aVLLR4XYxFKaA==,iv:ZH7FubPlGyAFSg8udQwLuUGo4NLr5/Zr49sx4kcFuVI=,tag:ZtfJrmuuA967Jv/b9XjxQA==,type:comment]
apiVersion: ENC[AES256_GCM,data:/eU=,iv:8bHQkR0R2NHGzQRhdJAy9l0pbZawkee2z2W7xmk4l9I=,tag:OziwaorOtiTeiElj3099Og==,type:str]
kind: ENC[AES256_GCM,data:St6dpozv,iv:HS6SLi/+6VxZprB58Wz2vRttiFR8GyBL4rVjLnpgO94=,tag:7SNNjc11ntPH7vZ8Tu1uvw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bVwQ0Cjy/PhQJq0cXcE=,iv:h54QUy3qD9awPL2jYo2Kre1wq/Pq2m12VEdDR3O4cqA=,tag:W6w7VtuOHjCL9WXfyiAOWg==,type:str]
    namespace: ENC[AES256_GCM,data:l9lkE2d2si3v,iv:Ab/cvo9gfT+3sLVL404242ig37Void7JngfNhbt1Xw4=,tag:wDm5iyAk1R0PXWR8zaZmmw==,type:str]
type: ENC[AES256_GCM,data:hiE7Lk3T,iv:wTMCFyKqBQPlJmGaD4OhVdJJx/dDAgOgqk+4WmI40ME=,tag:iQxDNxwGIN8xYgROMdWnEQ==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:v+hEvEXnW1Y7dGOZY32EQ5k=,iv:HnSrfuWWRvfJFDb0qYjSJfLcihaix2MdnS3oDZ0E/70=,tag:eei3/hklOb0ug1hGp2w9DQ==,type:str]
    client_secret: ENC[AES256_GCM,data:02e9TDtDGbTLND3x2UxELpukz+J88A+CWeNHhkm79sMf6XfpwV5zWLWBRnS8a9r6NY15UH8cPmVeZ26txOu6,iv:imUjEGxKdWHOZaqAS2ZNSDVAvpvaXbN91lv1eDm7gOI=,tag:hMfIROGfXEQTevnO0scmlA==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0tKMkU2NWF5a1pLNW1v
            ZjV3dS9sb3pBWm1PajU2NjlwRER6UG5Mbkc0Ci82bjgrNWNwRkZzdWdzaDltNXpm
            RFNrRXlpdXhjSEFSR1QweXJ0aHFoWjgKLS0tIHFmb3h0aFprVmVqZWlKVmIvSjVs
            K3ZpckwyZDRlNVFHSjQydUc5MS9WdkkKmxhuDwuiT6Ny7OghPfRv5DnfTI+ZsXfH
            +E+QnxUS64LNUMfSejHaETwQkqKcGg1qt4lDIhCk5MaZdKRRoHR20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T16:48:15Z"
    mac: ENC[AES256_GCM,data:yJmm0aMKReA3Elnf2LjEp9AGWZ2zYTOtTv7hCnmK8kChlzqwZDwi8b7CbBQzx/tpybwOm+zahAd1gsOVoboQqoXd2gFFLzV/RyEgqrWdaQydxKiripUPbza28dV7tzdsXZne6m4ImO4rxH5duNJxz3aptboSGiA/yzZTA9Q3G6Q=,iv:HP30H6yeOQEK9X3G+uP+deFWEIYuueukhE+N/+kL1dM=,tag:dD3DvzMhTnHGBoxwnfS42A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:ovw=,iv:RqRGI8K+X/BFu3Ut5uAZgTAQv8pdbOd1W112vQGDmG0=,tag:4x+PseRXyEdLFP2+eq5+iQ==,type:str]
kind: ENC[AES256_GCM,data:nBRDSdZt,iv:goD/E92XNz0/Bjt54Z8gtvDlUxs29h1//Mj5kGXWT1Y=,tag:qJrDyRb2/z4GBwgpge2PdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S5LoyEmyHcu9uA==,iv:lsXdUEnwnX6baz+iVnaq+6ZKEnmPNixNy4X5FrmjB+c=,tag:BVm+dJ+pCuFt/HxXTq4+DQ==,type:str]
    namespace: ENC[AES256_GCM,data:fT/FKuX/J7X6rg==,iv:SxZ9oI+d9GaPhy2o1giJsE1wRD3bK/Gsv81+uHzfLi4=,tag:mEsN656ie/TfOrvZTwuhVQ==,type:str]
type: ENC[AES256_GCM,data:/5QxbH/j,iv:fa9fiBWtX/0xFNCv4ufDfs3UZpSzKXDXU2rGoRV3ZrM=,tag:zp4k0g/3xgVcjFOHthD+CA==,type:str]
stringData:
    nextjs-auth: ENC[AES256_GCM,data:I/Kb0RVppvF7Wt78eROGklNP3Cwp,iv:9RDLZP6UbM8QNXFXVk4ZaSmSWyIqGjB4tUwJeavMRFs=,tag:nESUP0hp0hHs7Ta/R3sxsQ==,type:str]
    postgres-user: ENC[AES256_GCM,data:ND66LHvOj3/NHQ==,iv:DUUitCok/7vtOWiXbX91Qn6mzYwdxL3Rm97AuweoqJk=,tag:J+7IPxeV8M7pfPKxkFPgyg==,type:str]
    postgres-passwd: ENC[AES256_GCM,data:XatJk8LNRFX61CZaEROnVcG8+aHe,iv:Km8racQtnuUlkCFxr0wiVf+SeOrwt6ikEbrG+wHyOi4=,tag:/IQBgIzTv8EYybRFa69Kag==,type:str]
    email-server: ENC[AES256_GCM,data:qpg4svlvJrLwnPFaiBEyWx1UrFsA++59E42F5aeHNuTq2xsfdQt3Sppkuj72Ba91H5ya1PJekowpm2A2yS4Hkpc=,iv:E35IlqbYXH3nH6ndS/vtAKpxfKvHmXxk2hbxxfXlLjk=,tag:8k4wQjcKdXpNdwLUMpnrig==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0tKMkU2NWF5a1pLNW1v
            ZjV3dS9sb3pBWm1PajU2NjlwRER6UG5Mbkc0Ci82bjgrNWNwRkZzdWdzaDltNXpm
            RFNrRXlpdXhjSEFSR1QweXJ0aHFoWjgKLS0tIHFmb3h0aFprVmVqZWlKVmIvSjVs
            K3ZpckwyZDRlNVFHSjQydUc5MS9WdkkKmxhuDwuiT6Ny7OghPfRv5DnfTI+ZsXfH
            +E+QnxUS64LNUMfSejHaETwQkqKcGg1qt4lDIhCk5MaZdKRRoHR20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T16:48:15Z"
    mac: ENC[AES256_GCM,data:yJmm0aMKReA3Elnf2LjEp9AGWZ2zYTOtTv7hCnmK8kChlzqwZDwi8b7CbBQzx/tpybwOm+zahAd1gsOVoboQqoXd2gFFLzV/RyEgqrWdaQydxKiripUPbza28dV7tzdsXZne6m4ImO4rxH5duNJxz3aptboSGiA/yzZTA9Q3G6Q=,iv:HP30H6yeOQEK9X3G+uP+deFWEIYuueukhE+N/+kL1dM=,tag:dD3DvzMhTnHGBoxwnfS42A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:TAE=,iv:t4Y+KAKbPIIpxqkcLjdJnkn3frVuyKFJgUrchVhC3bY=,tag:kwQVtsj+Z7AC6kMbBuLbiQ==,type:str]
kind: ENC[AES256_GCM,data:rwH3UiRx,iv:hgKuNEY7oWuyu0BK80H2Hw/OtxvKJRs2dyZLJCyFoZA=,tag:HfDw41WKL4PHHdmDnQOiPA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P/xJqLXZ,iv:WYd8c6gIsV20BpN3UEYilGgEW2IDuxQJ/M75WNOSWtI=,tag:A9ZxcOhCKwQdG3UO9OBRZg==,type:str]
    namespace: ENC[AES256_GCM,data:Gf4Dxo3QBtlD4XoPLjuV,iv:S9qsPy8ZpPDgV6uw/yif/4H71WNDXK5jxmgMNAyWANw=,tag:XOiaaFKimLjGwDlGfS9BOQ==,type:str]
type: ENC[AES256_GCM,data:jnWul4jy,iv:K4cc85t2Dtl552ISOAN9u34MAi5zlr3xrtqrnc+NeBY=,tag:CLh4VbixLICAzpZ30ZK0kQ==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZaCe6YAY4QPSq0QcvbfdSPCJOtpw3Aaz/74=,iv:qBYXpnowuEuFdUFfWhiWT3pxprFRuMQrCMbnnPOFRdE=,tag:RLI5FuqbO23GYVvsKoi4eA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:c30CVju5hr3togJG/gov9w/l1YvyOYdOhCgBq2oPxebmdz5u1x+G4SeECIAt71Vl6ACKheFQYPSTkecu9fnFTw==,iv:FabD7C4+ge5jecgS3flzcNYidca/7lsmJZ2AC0bOL6I=,tag:L6uN2QQ04tVoJRJHLEzDOQ==,type:str]
    #ENC[AES256_GCM,data:jo/C+41A0rbVF4vizG0/PrjBAcXEtYvwK9XfyjMdWcGS,iv:GSgeNcNZ/RrryhHjflnVOg0HV8WXgI2fySBqUohr43w=,tag:80vtB0HTebMQ0l1UqbJHgw==,type:comment]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:OjR0zpJr6OcpInV9lMS9+15R,iv:wUIFIMZ2ekpSyjnBdD3mcXVVhtG5lBy629y1TuNDA7w=,tag:fg3o/tLqdMPKCPvad314BQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:+q9gAHfq,iv:R9KV+qqfUNJRLZDHZldBfa8EAP68oySyUU9tAkvhaVs=,tag:K6EQStRSn5mKYGu4XJvKCw==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV0tKMkU2NWF5a1pLNW1v
            ZjV3dS9sb3pBWm1PajU2NjlwRER6UG5Mbkc0Ci82bjgrNWNwRkZzdWdzaDltNXpm
            RFNrRXlpdXhjSEFSR1QweXJ0aHFoWjgKLS0tIHFmb3h0aFprVmVqZWlKVmIvSjVs
            K3ZpckwyZDRlNVFHSjQydUc5MS9WdkkKmxhuDwuiT6Ny7OghPfRv5DnfTI+ZsXfH
            +E+QnxUS64LNUMfSejHaETwQkqKcGg1qt4lDIhCk5MaZdKRRoHR20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T16:48:15Z"
    mac: ENC[AES256_GCM,data:yJmm0aMKReA3Elnf2LjEp9AGWZ2zYTOtTv7hCnmK8kChlzqwZDwi8b7CbBQzx/tpybwOm+zahAd1gsOVoboQqoXd2gFFLzV/RyEgqrWdaQydxKiripUPbza28dV7tzdsXZne6m4ImO4rxH5duNJxz3aptboSGiA/yzZTA9Q3G6Q=,iv:HP30H6yeOQEK9X3G+uP+deFWEIYuueukhE+N/+kL1dM=,tag:dD3DvzMhTnHGBoxwnfS42A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
