#ENC[AES256_GCM,data:BebG31oZppeCvObL0DHgrQQbtehrFU4c5k4++iXDHLY=,iv:ExNRE4UMUD77dA/2vS0dDM/UIbfL9WWOrJdXMV2vQAs=,tag:mOuMEUX0fjmJFhfa6xurFw==,type:comment]
#
#ENC[AES256_GCM,data:SB+ruW9ffA==,iv:bJWwXSuf1RiQqi1VGOY60v+iUDGizn8RBtqS+HViQX8=,tag:3tPkSj7giC1X+tjcmRBWUA==,type:comment]
#ENC[AES256_GCM,data:BU58FK1809GdiDA+KJUJlQ/AfkF0o6fr6/yPoHTVBL02sA2RtwWh,iv:sdKs9gPZTEco4nPXUxZKdy3lniXZohKQPqrIkRf5Kww=,tag:fhkonpLnC/1hbKkMPlkMdg==,type:comment]
#ENC[AES256_GCM,data:hn4uULZhHASQfAKgkbKCh41SBUrvglWfaZ6azcxypHC4tg==,iv:APVo60ia5W5BcB3e3GD22XuZprufc05y98r0sm7LPTk=,tag:xRitbQgTtZ0ULRkVMZZPkw==,type:comment]
#
#ENC[AES256_GCM,data:BgEW0cqzBc3oE9MOskOUb3sNGYnGa0m23bVFFH8dWM0iESeH6L11WZYZy34i55nXfaX+TXH/eHhoZLV+A41oOl6/5DdrA++I,iv:PzkXs1aNAyRXX9s9NCvWEvpWcFS8Nvtj+rAGp2UpKzw=,tag:Y/ke+b2g8lmob8WDTQUvPA==,type:comment]
#ENC[AES256_GCM,data:WkYBgQ2qncfBmV5iUCWsqFmxlt90Tr7+EEEPWdpvmbeVh0SE9A==,iv:dqQ0ZH6/qsJ04oHSjaYkIDFdeHVk2ZNHkzf/FFZrwj4=,tag:Hr2UORVLVxJrHPP6qovOLA==,type:comment]
#ENC[AES256_GCM,data:w2ShBSFFz+MVZcwcquuua+Wh4WtYLg==,iv:P2tPsu5VjZJt2Ha7AmfHsaytaDkrKAJ5pncSzxJUka8=,tag:nte9vnaoNA+Cr92ZIg0Mlg==,type:comment]
#ENC[AES256_GCM,data:54vVFBgMBhG7IIe+IgHVJ0U=,iv:6fqCx7f8SAO2zowT7LNl6s3CjFfR7SjTtlpbxwlQ41Q=,tag:zDiH7yto8hdr8kcysiuosw==,type:comment]
#ENC[AES256_GCM,data:qeVytC42iAUbjicb+4LxZJEhJZLS3pauv48FmyA//xiZ6Mw=,iv:1qckidSlq/r3gpJwt8NYoKCjUJjJ6w03AL0XzyWxmMc=,tag:2Axj9OtaQp7fx1bGff2eMQ==,type:comment]
#ENC[AES256_GCM,data:QjckNgwKgtIoAMljG3AX+heKec105buNEH85mnnn0xR9iluE21Di5V8LHaLuBOXDDgsTOMo=,iv:wNe+iBOr1e0rFp2BK+aPH/69f9pad8M9xVJbPDWhI1M=,tag:pNtfId0uI1jmUI4jr89Y+w==,type:comment]
apiVersion: ENC[AES256_GCM,data:+SA=,iv:ASXSw8Td28G8qQitUSlML+p0XWXOVOHnKOJ5uUtGJQU=,tag:+0WfHfK6PX0eGWdpaOo9zA==,type:str]
kind: ENC[AES256_GCM,data:kZEywsTD,iv:3JqZqht0ilSTtGEYySCHv1uh0u77O61QmG0vSocXVp0=,tag:YPcg1DkLSUXLgmJf/5we5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fVCJps2uRkAfL78VkYVFvwj5Vw==,iv:Ss27SC/mZ/L0FYEx/8fuSBYlSsbJ+U64ytoeYELHdTU=,tag:Dl4i4Cw5EMRVosZwHnr/ww==,type:str]
    namespace: ENC[AES256_GCM,data:Y6LwSlco1wSJS8+M,iv:AuT1XX9/S8/RkvF1rwKYMcdKAgHQQWIHNTbf8b8IeTA=,tag:3ikIsvDLXS2L51zNBctxtw==,type:str]
type: ENC[AES256_GCM,data:ClcHap/Q,iv:WGNm880oV1YSRlkD+8ul0/RwW6DIG2XFbTHF2AxuXqU=,tag:GOEWLWlj9AL7APDyC6orfg==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:BHVN8FLyeS2TppeaC+3A+xEZ/oQ=,iv:+j0ZPqVUkAQVUiv3X9em9dm7LvNKyEdbXkYF0GaX4Cw=,tag:DU3LZGWZUvl+5Jhy04EdPg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:MjlAFJT7aD8qObvYdlYXXRaGypZxTItYz8SO1CgQdMtQ0K3N9x5uLA==,iv:ccJhOoMffk7JiDR5SLdojmtKUn6xTE5a+sbBO53/ObI=,tag:7qlRahbecX1QcSOCCOH2OQ==,type:str]
    hosted-zone-id: ENC[AES256_GCM,data:tnZGOqplwKcJEr0yWkd420gewD8=,iv:z3mlely8XOb7Sg5Dfv0CH/TRvOczyc+v9OYnQ8yFke8=,tag:fI/gjF0FCPh+WmSAO47EAw==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUlFGa0ZsY2pSVXVrdGI4
            UkZoazNYRmFRcGVJT3lENzkxYXZaQ0JWMEFZCmdCaElsVkpxbzR6TWc3Z0F0L0ZL
            cDI1Q3lKMVdmTldWV25kUEh0Z2laY00KLS0tIGpqMjEvZVdQTHRXc0lsaERUZVhn
            N0o3dzVjV1VXL2phN1RUdE80NzNXUFUKvYIPQB+dJsJ4E/nRalm0VMXWzo7plLng
            kwdJ/2h9/2UqfGlD3F1K3yrElp9a6gPIoaHjzQ6qD4bCob4LB2PLtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T10:14:02Z"
    mac: ENC[AES256_GCM,data:62wyzNrsyo1/uU9LuVxFvB7mCTJe7/ymUcCAH7JZVOZ3b8K75rMAkbnGGHWLHphej7+5nQLdfWK18tf2UQ/XxDGppK6E5QQDJGtfRqkvnk+ffhk5oPq6lINcIollD6PIKNJArQ3L7M2vuEp1YxEZiOQn5ZdueC9ffHO+s84blFo=,iv:nRF+o8A0xGG7Kij1JC5l7+oG20wXEOotlQNWiqHw7+k=,tag:35HY2dJSac+Ph0J9Q/S12g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:RRjaRjs7rN/ovj0aCKr2P/OqrxetxZ6kl4Ileiv1cY+rqwQS1vv1GQQNY6SqyZAK,iv:a3L3+YnJW5jJndPXVwtDLQOk8RO+eaTVIbp2XvadTqA=,tag:hwkN7b6Dy/+zZagFuzflIQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:+SA=,iv:ASXSw8Td28G8qQitUSlML+p0XWXOVOHnKOJ5uUtGJQU=,tag:+0WfHfK6PX0eGWdpaOo9zA==,type:str]
kind: ENC[AES256_GCM,data:kZEywsTD,iv:3JqZqht0ilSTtGEYySCHv1uh0u77O61QmG0vSocXVp0=,tag:YPcg1DkLSUXLgmJf/5we5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZCnYOXZvKTJUM0bXdw==,iv:+j8nUGm6pJNDa4BM2DfyLZ6qaaiZY93isIx1qKcJCls=,tag:f7KDUCfTChE4SvpVXrP/dA==,type:str]
    namespace: ENC[AES256_GCM,data:NIYlL3sx,iv:1HAZOU+peMbFCJfynAvEIjWjkgMIceVFAASl36WLXsI=,tag:Fe6R1bXLfaVSXNGd9FLv9g==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:/JwUUlY4h7pWcWSZVA==,iv:3npTd0Cvc9zUmqj/ZUBhED7WBkoCnbqEDIT60uQ9DQE=,tag:ep/YIA3NsyjLC4FZzfN+FQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:tQMD7AOb,iv:FaS+fQ2YZVzm4Nrl6nSOEJpt1Et40BYns1ksWagmhiI=,tag:muPAkChurPLB78wSyDj8uw==,type:str]
type: ENC[AES256_GCM,data:ClcHap/Q,iv:WGNm880oV1YSRlkD+8ul0/RwW6DIG2XFbTHF2AxuXqU=,tag:GOEWLWlj9AL7APDyC6orfg==,type:str]
stringData:
    server.secretkey: ENC[AES256_GCM,data:yuka0phSTIXNWxqqb52ajy4QQ3rOocZYxgzHWLFEizeeIHRox+3PlZUAKRo=,iv:JNHXqotmm73mXgcOqrgbNHgDqvG/4D8/GnUe/P1z7Kk=,tag:fYXg2F1qUvWrXJ9AvSacQg==,type:str]
    admin.password: ENC[AES256_GCM,data:Dr7wEIrGWfQK3V6Z1tyjFSS1NLgbOi86z2Z4vbNnxg2eRUCzhTm8YKgaQYosYePgEH8UMiBMi1a6RnLUkIJmC4BRfz7PioXOMZTwXOlKVbFW3c17fV5f19uvkv21WbonRncoBbQkW0VmultAyiok+JSTeWQvK8fiXgnvludiRR0kBmN98exho1Q4KcEsoA7azZaFP45NNZYojspVcXMxJMHTtKNOY6hYXtMFLQ==,iv:BroNaBr/d+u7S+6mIY0TK8tlCFoUq8FFQ/qC+QbYV5s=,tag:gyoJLfWfILGDeN6k4n7Xaw==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:SDN6g0ivAjW+bJhkb3ZrKkxu7kI=,iv:oCoCbCTKV6CTwiwhVb3CZB1bG0Eo00o2yWYImGxnu5w=,tag:UZQW7o9pzDdnBw98SLyhKw==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUlFGa0ZsY2pSVXVrdGI4
            UkZoazNYRmFRcGVJT3lENzkxYXZaQ0JWMEFZCmdCaElsVkpxbzR6TWc3Z0F0L0ZL
            cDI1Q3lKMVdmTldWV25kUEh0Z2laY00KLS0tIGpqMjEvZVdQTHRXc0lsaERUZVhn
            N0o3dzVjV1VXL2phN1RUdE80NzNXUFUKvYIPQB+dJsJ4E/nRalm0VMXWzo7plLng
            kwdJ/2h9/2UqfGlD3F1K3yrElp9a6gPIoaHjzQ6qD4bCob4LB2PLtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T10:14:02Z"
    mac: ENC[AES256_GCM,data:62wyzNrsyo1/uU9LuVxFvB7mCTJe7/ymUcCAH7JZVOZ3b8K75rMAkbnGGHWLHphej7+5nQLdfWK18tf2UQ/XxDGppK6E5QQDJGtfRqkvnk+ffhk5oPq6lINcIollD6PIKNJArQ3L7M2vuEp1YxEZiOQn5ZdueC9ffHO+s84blFo=,iv:nRF+o8A0xGG7Kij1JC5l7+oG20wXEOotlQNWiqHw7+k=,tag:35HY2dJSac+Ph0J9Q/S12g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:EZX2pfyjiIJ8TLvjhtmsq91jEhaJsuAhxbCTeCP6//FL7P7TH81AqOVXvpic21o=,iv:xGqjT8OnAK95cVtkNWLXyZoRxWv1hG3rsEEnaOmjYek=,tag:RcmGnFMISkfF0Lx4/Ldgig==,type:comment]
apiVersion: ENC[AES256_GCM,data:+SA=,iv:ASXSw8Td28G8qQitUSlML+p0XWXOVOHnKOJ5uUtGJQU=,tag:+0WfHfK6PX0eGWdpaOo9zA==,type:str]
kind: ENC[AES256_GCM,data:kZEywsTD,iv:3JqZqht0ilSTtGEYySCHv1uh0u77O61QmG0vSocXVp0=,tag:YPcg1DkLSUXLgmJf/5we5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sriVTGJ9k4bcAC2Y,iv:kJ6yXcXaxXr8s7ApagtTgdK6KwaQZbWWsp+FVmDnES0=,tag:A9K/jdGljUM0b0rnENSDXg==,type:str]
    namespace: ENC[AES256_GCM,data:NIYlL3sx,iv:1HAZOU+peMbFCJfynAvEIjWjkgMIceVFAASl36WLXsI=,tag:Fe6R1bXLfaVSXNGd9FLv9g==,type:str]
type: ENC[AES256_GCM,data:ClcHap/Q,iv:WGNm880oV1YSRlkD+8ul0/RwW6DIG2XFbTHF2AxuXqU=,tag:GOEWLWlj9AL7APDyC6orfg==,type:str]
stringData:
    keys.txt: ENC[AES256_GCM,data:3rYOIKJ/8j+mQp3eRNdCNo8yFC/P0KpBDmZnmZL1hc1Q58TNDii5EMnPYsWFCq+OjGCwYXQpGTHV7xUSKa29Q1oxjuUOL4jZSxPD,iv:ErbPfmOcLajTFX+iA7EpLYUMx839tIPrCIna5+JNggc=,tag:Ub4+5BqbSL99Gx9eaGw+aA==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUlFGa0ZsY2pSVXVrdGI4
            UkZoazNYRmFRcGVJT3lENzkxYXZaQ0JWMEFZCmdCaElsVkpxbzR6TWc3Z0F0L0ZL
            cDI1Q3lKMVdmTldWV25kUEh0Z2laY00KLS0tIGpqMjEvZVdQTHRXc0lsaERUZVhn
            N0o3dzVjV1VXL2phN1RUdE80NzNXUFUKvYIPQB+dJsJ4E/nRalm0VMXWzo7plLng
            kwdJ/2h9/2UqfGlD3F1K3yrElp9a6gPIoaHjzQ6qD4bCob4LB2PLtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T10:14:02Z"
    mac: ENC[AES256_GCM,data:62wyzNrsyo1/uU9LuVxFvB7mCTJe7/ymUcCAH7JZVOZ3b8K75rMAkbnGGHWLHphej7+5nQLdfWK18tf2UQ/XxDGppK6E5QQDJGtfRqkvnk+ffhk5oPq6lINcIollD6PIKNJArQ3L7M2vuEp1YxEZiOQn5ZdueC9ffHO+s84blFo=,iv:nRF+o8A0xGG7Kij1JC5l7+oG20wXEOotlQNWiqHw7+k=,tag:35HY2dJSac+Ph0J9Q/S12g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:zmlyitt0h3+Z290flBOjrA==,iv:egRC2ioaEON8P6NWlamrjGWDoB1Y+ZmdMA1F1GtujPc=,tag:WAJkXY920+uIAeYdCdUvOA==,type:comment]
apiVersion: ENC[AES256_GCM,data:+SA=,iv:ASXSw8Td28G8qQitUSlML+p0XWXOVOHnKOJ5uUtGJQU=,tag:+0WfHfK6PX0eGWdpaOo9zA==,type:str]
kind: ENC[AES256_GCM,data:kZEywsTD,iv:3JqZqht0ilSTtGEYySCHv1uh0u77O61QmG0vSocXVp0=,tag:YPcg1DkLSUXLgmJf/5we5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PNFrOEnC0Z7rcw==,iv:peoB/cKa4g5BjpCL2TR4YnRxpaQngilU8S+Yzxl6U8Y=,tag:+WxiZebimb80C/g5g6kQHg==,type:str]
    namespace: ENC[AES256_GCM,data:Fs1/vg0=,iv:XiojDHMG3av4n5CMT1Ctq3Ydj50mKbzkltWJ/aJcCQY=,tag:w1XrGXDi+Ci1MhU9iKCIvg==,type:str]
type: ENC[AES256_GCM,data:ClcHap/Q,iv:WGNm880oV1YSRlkD+8ul0/RwW6DIG2XFbTHF2AxuXqU=,tag:GOEWLWlj9AL7APDyC6orfg==,type:str]
stringData:
    plexserver.claimcode: ENC[AES256_GCM,data:p34uKMlF4wUW3tzpb6thn0whb27NF6IsunI=,iv:VU+V+J1qLNjP5Ykg/wQ6IgM0XDM88DDkkzJw8jHJ7XM=,tag:HjG2iJaSwOxF/4nOSmUKOA==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUlFGa0ZsY2pSVXVrdGI4
            UkZoazNYRmFRcGVJT3lENzkxYXZaQ0JWMEFZCmdCaElsVkpxbzR6TWc3Z0F0L0ZL
            cDI1Q3lKMVdmTldWV25kUEh0Z2laY00KLS0tIGpqMjEvZVdQTHRXc0lsaERUZVhn
            N0o3dzVjV1VXL2phN1RUdE80NzNXUFUKvYIPQB+dJsJ4E/nRalm0VMXWzo7plLng
            kwdJ/2h9/2UqfGlD3F1K3yrElp9a6gPIoaHjzQ6qD4bCob4LB2PLtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T10:14:02Z"
    mac: ENC[AES256_GCM,data:62wyzNrsyo1/uU9LuVxFvB7mCTJe7/ymUcCAH7JZVOZ3b8K75rMAkbnGGHWLHphej7+5nQLdfWK18tf2UQ/XxDGppK6E5QQDJGtfRqkvnk+ffhk5oPq6lINcIollD6PIKNJArQ3L7M2vuEp1YxEZiOQn5ZdueC9ffHO+s84blFo=,iv:nRF+o8A0xGG7Kij1JC5l7+oG20wXEOotlQNWiqHw7+k=,tag:35HY2dJSac+Ph0J9Q/S12g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:zmlyitt0h3+Z290flBOjrA==,iv:egRC2ioaEON8P6NWlamrjGWDoB1Y+ZmdMA1F1GtujPc=,tag:WAJkXY920+uIAeYdCdUvOA==,type:comment]
apiVersion: ENC[AES256_GCM,data:+SA=,iv:ASXSw8Td28G8qQitUSlML+p0XWXOVOHnKOJ5uUtGJQU=,tag:+0WfHfK6PX0eGWdpaOo9zA==,type:str]
kind: ENC[AES256_GCM,data:kZEywsTD,iv:3JqZqht0ilSTtGEYySCHv1uh0u77O61QmG0vSocXVp0=,tag:YPcg1DkLSUXLgmJf/5we5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:a7L0DcJUqNMg9Xw46CRrOHx3TsK7,iv:g2EF1RWM2DFX1l9+rUu0MpKm8EHS26TkjOK9pHB4hFU=,tag:tvTCimMFg1PEAOk5oOw5qg==,type:str]
    namespace: ENC[AES256_GCM,data:aS3v39vKdLlCiA==,iv:IkfLhMpqX7KY4vZr5S7m8Esx0ZT6W4yy7FSX8rT9lxI=,tag:bXheFjefnbWfaxOEGTuA3A==,type:str]
type: ENC[AES256_GCM,data:ClcHap/Q,iv:WGNm880oV1YSRlkD+8ul0/RwW6DIG2XFbTHF2AxuXqU=,tag:GOEWLWlj9AL7APDyC6orfg==,type:str]
stringData:
    bot-token: ENC[AES256_GCM,data:r9ar4LTDjSYAq/E5YiFwMz8B5PyG+uWCmMCIvtDdUai5w36fBj1SggGfM0utRg==,iv:bfSsi+LZ8LNqiOOBlfZyVs1hPdEizN0eLpUn1zjw9go=,tag:scQioG5J/C04AcCnJ1I8JQ==,type:str]
    chat-id: ENC[AES256_GCM,data:oEzjHZc1Rl4iYw==,iv:6KC9ADHfVHIjle/2a6/jSTm4/vocx3tkEl8SmOyCwJE=,tag:lp8Roamnd0Tui159unrRHA==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUlFGa0ZsY2pSVXVrdGI4
            UkZoazNYRmFRcGVJT3lENzkxYXZaQ0JWMEFZCmdCaElsVkpxbzR6TWc3Z0F0L0ZL
            cDI1Q3lKMVdmTldWV25kUEh0Z2laY00KLS0tIGpqMjEvZVdQTHRXc0lsaERUZVhn
            N0o3dzVjV1VXL2phN1RUdE80NzNXUFUKvYIPQB+dJsJ4E/nRalm0VMXWzo7plLng
            kwdJ/2h9/2UqfGlD3F1K3yrElp9a6gPIoaHjzQ6qD4bCob4LB2PLtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T10:14:02Z"
    mac: ENC[AES256_GCM,data:62wyzNrsyo1/uU9LuVxFvB7mCTJe7/ymUcCAH7JZVOZ3b8K75rMAkbnGGHWLHphej7+5nQLdfWK18tf2UQ/XxDGppK6E5QQDJGtfRqkvnk+ffhk5oPq6lINcIollD6PIKNJArQ3L7M2vuEp1YxEZiOQn5ZdueC9ffHO+s84blFo=,iv:nRF+o8A0xGG7Kij1JC5l7+oG20wXEOotlQNWiqHw7+k=,tag:35HY2dJSac+Ph0J9Q/S12g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:ZoyctMxCh8A6Iyt37L3ZJWcguMiwzMvDIri6fp4ros7/bS050Q==,iv:xE8y20T340soPUbSvt7mR8Vi+F9bAto943Pyxd/Byfs=,tag:CT2WoXqU9k1ugV+FMKfwKA==,type:comment]
apiVersion: ENC[AES256_GCM,data:+SA=,iv:ASXSw8Td28G8qQitUSlML+p0XWXOVOHnKOJ5uUtGJQU=,tag:+0WfHfK6PX0eGWdpaOo9zA==,type:str]
kind: ENC[AES256_GCM,data:kZEywsTD,iv:3JqZqht0ilSTtGEYySCHv1uh0u77O61QmG0vSocXVp0=,tag:YPcg1DkLSUXLgmJf/5we5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s4q3IQa5ZOnliJ/Mlhg=,iv:rMvzYLQYImhZ/Cysp3PMbAW8RRUc84U2S/2u3ToU6uA=,tag:AuwXEhU+M1Kwr1QCvTJvZQ==,type:str]
    namespace: ENC[AES256_GCM,data:tbrxiVwtGSWt,iv:EbX86zL6DWSriQgkIIa8L1j0XkvdvyQDAdCEBPRiR4E=,tag:GhG7yVU/zITDElFx+nLF4g==,type:str]
type: ENC[AES256_GCM,data:ClcHap/Q,iv:WGNm880oV1YSRlkD+8ul0/RwW6DIG2XFbTHF2AxuXqU=,tag:GOEWLWlj9AL7APDyC6orfg==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:JNeNegot82ACxuWJPyzA9bg=,iv:bmxZqdYQp/BM8nMv5YEmgdPKPmh0dnosSd+vqtBk04w=,tag:2oYBtFOeXwf/hYzqu5C7DA==,type:str]
    client_secret: ENC[AES256_GCM,data:NPAxFtaxG2f8r0kdNAFTUIfXfJtIl/MxIAt2bRfRZkhTT+cxQhkehjFDe3j3R2wzjAK6Z/eQzf/jcMcyceSg,iv:53IZILy7bt6HKrTDcvae8fJcY7qZ6RrWhcLPIHiiZVM=,tag:qd2DcmeecIFkEc8J5sCzsA==,type:str]
sops:
    age:
        - recipient: age1e03zgm5ewe4rckxnw6rqe90gpj6jk5e9l2sct6e4msk5w0xhx9vqhrsass
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUlFGa0ZsY2pSVXVrdGI4
            UkZoazNYRmFRcGVJT3lENzkxYXZaQ0JWMEFZCmdCaElsVkpxbzR6TWc3Z0F0L0ZL
            cDI1Q3lKMVdmTldWV25kUEh0Z2laY00KLS0tIGpqMjEvZVdQTHRXc0lsaERUZVhn
            N0o3dzVjV1VXL2phN1RUdE80NzNXUFUKvYIPQB+dJsJ4E/nRalm0VMXWzo7plLng
            kwdJ/2h9/2UqfGlD3F1K3yrElp9a6gPIoaHjzQ6qD4bCob4LB2PLtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T10:14:02Z"
    mac: ENC[AES256_GCM,data:62wyzNrsyo1/uU9LuVxFvB7mCTJe7/ymUcCAH7JZVOZ3b8K75rMAkbnGGHWLHphej7+5nQLdfWK18tf2UQ/XxDGppK6E5QQDJGtfRqkvnk+ffhk5oPq6lINcIollD6PIKNJArQ3L7M2vuEp1YxEZiOQn5ZdueC9ffHO+s84blFo=,iv:nRF+o8A0xGG7Kij1JC5l7+oG20wXEOotlQNWiqHw7+k=,tag:35HY2dJSac+Ph0J9Q/S12g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
