apiVersion: v1
kind: Service
metadata:
  name: opengym
  namespace: opengym
  labels:
    app.kubernetes.io/name: opengym
spec:
  selector:
    app.kubernetes.io/name: opengym
  ports:
    - name: http
      port: 80
      targetPort: http
