apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestash
  namespace: filestash
spec:
  template:
    spec:
      initContainers:
        - name: config-generator
          env:
            - name: APPLICATION_URL
              value: "https://drive.etcd.me"
            - name: OIDC_CONFIG_URL
              value: "https://auth.etcd.me/realms/homelab/.well-known/openid-configuration"
      containers:
        - name: filestash
          env:
            - name: APPLICATION_URL
              value: "https://drive.etcd.me"
