# Keycloak Realm Import - etcd.me overlay
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: homelab-realm
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  keycloakCRName: keycloak
  realm:
    realm: homelab
    enabled: true
    sslRequired: external
    registrationAllowed: false
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    resetPasswordAllowed: true
    editUsernameAllowed: false
    bruteForceProtected: true

    clientScopes:
      - name: openid
        description: OpenID Connect scope
        protocol: openid-connect
        attributes:
          include.in.token.scope: "false"
        protocolMappers:
          - name: sub
            protocol: openid-connect
            protocolMapper: oidc-sub-mapper
            consentRequired: false

      - name: profile
        description: Profile scope
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
        protocolMappers:
          - name: family name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: lastName
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: family_name
              jsonType.label: String
          - name: given name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: firstName
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: given_name
              jsonType.label: String
          - name: username
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: username
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: preferred_username
              jsonType.label: String
          - name: full name
            protocol: openid-connect
            protocolMapper: oidc-full-name-mapper
            consentRequired: false
            config:
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"

      - name: email
        description: Email scope
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
        protocolMappers:
          - name: email
            protocol: openid-connect
            protocolMapper: oidc-usermodel-attribute-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: email
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: email
              jsonType.label: String
          - name: email verified
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
            consentRequired: false
            config:
              userinfo.token.claim: "true"
              user.attribute: emailVerified
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: email_verified
              jsonType.label: boolean

      - name: roles
        description: Roles scope
        protocol: openid-connect
        attributes:
          include.in.token.scope: "false"
        protocolMappers:
          - name: realm roles
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
            consentRequired: false
            config:
              multivalued: "true"
              user.attribute: foo
              access.token.claim: "true"
              claim.name: realm_access.roles
              jsonType.label: String
          - name: audience resolve
            protocol: openid-connect
            protocolMapper: oidc-audience-resolve-mapper
            consentRequired: false

      - name: groups
        description: Map realm roles to groups claim
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "true"
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-usermodel-realm-role-mapper
            consentRequired: false
            config:
              multivalued: "true"
              userinfo.token.claim: "true"
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: groups
              jsonType.label: String

    defaultDefaultClientScopes:
      - openid
      - profile
      - email
      - roles
    defaultOptionalClientScopes:
      - groups

    # OIDC Clients with etcd.me domain
    # Keycloak generates secrets - retrieve from admin console after bootstrap
    clients:
      - clientId: grafana
        name: Grafana
        enabled: true
        clientAuthenticatorType: client-secret
        redirectUris:
          - "https://loki.etcd.me/*"
        webOrigins:
          - "https://loki.etcd.me"
        standardFlowEnabled: true
        directAccessGrantsEnabled: false
        publicClient: false
        protocol: openid-connect

      - clientId: argocd
        name: ArgoCD
        enabled: true
        clientAuthenticatorType: client-secret
        redirectUris:
          - "https://argo.etcd.me/auth/callback"
        webOrigins:
          - "https://argo.etcd.me"
        standardFlowEnabled: true
        directAccessGrantsEnabled: false
        publicClient: false
        protocol: openid-connect

    roles:
      realm:
        - name: admin
          description: Administrator role
        - name: user
          description: Regular user role

    defaultRoles:
      - user
