#ENC[AES256_GCM,data:KZY5qRRhA2mtlurBiTtnVJHG8sNIOJRVd6cMn3iNAcM=,iv:FCEQUKwJnykt9kP0ycARFPms+MlAm4/mkldp2Y9fFW8=,tag:8Skr3eUIExq+rG52IeosZQ==,type:comment]
#
#ENC[AES256_GCM,data:czbuBkUvJw==,iv:MZ9OuwfeBhE7f2XadFvhBZhLCQ7pV11C72VuJpN9iP0=,tag:ZqDEiv/5sU2hZdK6ul6C5w==,type:comment]
#ENC[AES256_GCM,data:gPVKJAKNstNtij/KdYMfxP0mf+2+X5umG/Of1iSuQclVRwFkFDno,iv:TIPOV5wGeI6cm/dOlO5OWASqBQGtP/I+LSV9P0vTADY=,tag:OmkFN2pyB5shtC96YEgixw==,type:comment]
#ENC[AES256_GCM,data:trR07TU/6wHpTp94V8HmSAQFsTuS8nJHnYwpMnHra8GppQ==,iv:UaivJesZnzeYJCiMWHky7/M3N37A9bSV8l1d/Eyu8eg=,tag:RPdfHnPEzzuD8iPcxdtCxQ==,type:comment]
#
#ENC[AES256_GCM,data:NmKjtircoIm49hsRkBA6gxiWgVDmKy9xXoYhhyCa6npIrJYt2PqLvacM9zI9xV8G8fUAR+eLxmuchvSsqFg+5N3c+lEjPk0J,iv:9iv/6+Y/P6liGCdy7v0owZ3gdDOP4X+lqok+HPR8Pvk=,tag:3K6ksVL7nf29g2brntdF0g==,type:comment]
#ENC[AES256_GCM,data:J3lQgbwVcj9lg+BxRbCHvGTmDNBhC/tiGsO8Noq7236ir0kFl7cO+KdGfvFs7JI8yAOto24=,iv:RQsEhA+xtcuYbvms5fCsssXLsDW5abj7bRfM1AARWRM=,tag:QNt1MDKkTN15VRm295GGIw==,type:comment]
#ENC[AES256_GCM,data:WV37VgvjuAALPNgSBgL3C5UHf5BJBpGDwcx0F/iEJfkZ2QnzbQ8ouJg/H9KSeyfqwQaK+WI=,iv:QSRlyGObjfdiQOa6nQpYTOZ0JRf77rC/vaAk5A9B/7Q=,tag:DBuOG8KvQiiH2OlxHtJ0aA==,type:comment]
apiVersion: ENC[AES256_GCM,data:9kI=,iv:8uXXF26eQhyuk6vaSf5TX5RktHT4NciBId+nRO7j4+k=,tag:DQHTvdDn+KUXh4aUfIWd9w==,type:str]
kind: ENC[AES256_GCM,data:aT1QzwwI,iv:HRyGs25NpH9gnmfkaruyURzGtan1Z4T99zUOD+/rzpI=,tag:vkJJFHdi8LBj+lem7dwAhw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iGRQ/sQiTckYyyZUMeKs6I23zA==,iv:nV9E5me69p43DFEZKZCsa24waFWaSQJ+2C193dB7uDo=,tag:akwsZHp36GNpYwug7CHjXA==,type:str]
    namespace: ENC[AES256_GCM,data:xbKZdrcAyqtZzyvB,iv:W1bOz4HjgLgIMqjT+LxqLl/59RqRtjA6Azrjc7EvQZc=,tag:IUKvYgoTmvNXDlzJRHpPWA==,type:str]
type: ENC[AES256_GCM,data:3rEoRPpt,iv:E4L0hNHWoWYz1khNoxF6vEp436KUdenuoT6FggbuhYA=,tag:IcHTJzlaum0l0J3ic5IaAg==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:H+sX495zEEsJ/MHAQcxbCaYN50M=,iv:Nu9bgrpFEme3Cd9ifQBvw4rHMLKJ7fJIRKOTkNKMdTM=,tag:uRHe/9feIXpIJmvsnNF9ig==,type:str]
    secret-access-key: ENC[AES256_GCM,data:EYjV1/BdudkmaXo2UxK7/a3TcHsTaJamplDcpMTjQOS1jgo7nzbYvA==,iv:aphnCSWa7A4IqmiGBmZr8kOwm0LGArjy/UfdPpm2lOU=,tag:peu/BuFGo/S3JzIQ7o4DJA==,type:str]
    hosted-zone-id: ENC[AES256_GCM,data:JraF7oLfoF8k0XVfMVpqhrdijLM=,iv:VXZdYDDsHYPEibfcn9XPy2Aoe5bwlRb94sJZXfwhoWU=,tag:XN5L+wy6NOCW4wObvGKaYg==,type:str]
sops:
    age:
        - recipient: age1m58w3a52776phxqzeyztezx09u4z7964ug0skf2rvzrzw63v2dhq602hcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWXJRbGhvd0R4QktsQzNN
            TnM5WTJJaTBXTThJM3kzSGs5a2tBNHlBa1NBCmxXS3JzU2pPYk91WEJ3cVRpekZo
            UFBZMnRtaWJtZHVDMUxzQi9DdUh5WlUKLS0tIEJLZDFSNGxWdjFRNEtBN0paR1RT
            Mk9pOUdLd3dHa1drZXpEYkFQYlI0LzgK1Co3WrZ1trtwqBeGPytTbz7SkpviZKlg
            shEG/J0aIg6UgmxsTjWcHVR2BIuIW3uqBB27kRqut/OwGiqVSeasTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T23:25:57Z"
    mac: ENC[AES256_GCM,data:klykjeeScsDgw6zWGd4cWKx5JuIpchw/EaiAkXTtVPKFxYXnxTEEahhzhjslHT6iC122Dcx9MvVmQEQ4bQAAAfD1my9rYV4X3SiMi/03zFWd0GSd4KObrXAHpzAesye+yN2GnIpLKBHLBl7Z9IgCmTxs4E4qfeP3Xpxs26zcie0=,iv:ye681aKY3N0eDSvqnuv8DQ6wyWC1DHxzg9EmGwv40/I=,tag:ehbp0sB17qhdYAiajsJQ4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:zY9gAoiFYQOoieHzsQqLuT9CK01L/V2tWisHb8I5SkE//yV6ivoVPw==,iv:l1Nh64Y2ID7diewoOhFK7kR3IndC27Q05ABcGk9XoA8=,tag:YI6o4mf4vTX9FiE1QsZeKA==,type:comment]
apiVersion: ENC[AES256_GCM,data:mvU=,iv:dO6RO+EZjSHXCIVY/8+Lf1tuxl2DGdMZQFMMN//Hj/c=,tag:IMsZF6SuJUT2YKcxcZfypg==,type:str]
kind: ENC[AES256_GCM,data:Im82ibOd,iv:N+OyjwxCZm5br9/8W1/hqC8H2yhQ7ZL49XvKDrB86uI=,tag:OoRI/JZPosUkcJwB1HjJ8w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4wndYsrSrL5m15Y6RyluBA==,iv:+ChYaui+U24AmAjvXYqyzN4959eOEBuQXwlLhfSQ6Z8=,tag:nlLaMPhOZFZ//MpAOGquLw==,type:str]
    namespace: ENC[AES256_GCM,data:5JQZ8wNLcIc=,iv:KlpN0ekN8VeyRBl1ooCEUXzpiSE88fp5kaN6Gli69MA=,tag:nVNFooGOi/dZWxFC5yQvFA==,type:str]
type: ENC[AES256_GCM,data:F9g6dxn9,iv:6QkMVhJeufcNuWVjJ+hlESe7GFNij0Hk4ThBcrfK724=,tag:qVpD2E62TO6LC8JPU22yvQ==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:XgpGraB7CpR9p4svhc3+T7YTIyzK4zT2mWpun5ugphw=,iv:fMjLpl7/MsUsT3KgEeox8cx47YHcnmu10H/N7SDmXwc=,tag:GKeVulw1/W0b7DJgsoJczg==,type:str]
    db-username: ENC[AES256_GCM,data:Vu0DM939Sr8=,iv:AGw+PZDoluccswMjSDQvySkMdM53KeQ04GYra88hQKU=,tag:gkVAIIkz4tQPlOq1rw8SOg==,type:str]
    db-password: ENC[AES256_GCM,data:Lq/k7n4gPp7dluAV3I2suCU/jkwcCNqGAPOPnMehbwE=,iv:FwPRjTXaqHSCm+4akdcOdNbT5uj4F2p88kQV7jxU+2c=,tag:brSoaeRKzMzVh2/gh5dyDQ==,type:str]
sops:
    age:
        - recipient: age1m58w3a52776phxqzeyztezx09u4z7964ug0skf2rvzrzw63v2dhq602hcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWXJRbGhvd0R4QktsQzNN
            TnM5WTJJaTBXTThJM3kzSGs5a2tBNHlBa1NBCmxXS3JzU2pPYk91WEJ3cVRpekZo
            UFBZMnRtaWJtZHVDMUxzQi9DdUh5WlUKLS0tIEJLZDFSNGxWdjFRNEtBN0paR1RT
            Mk9pOUdLd3dHa1drZXpEYkFQYlI0LzgK1Co3WrZ1trtwqBeGPytTbz7SkpviZKlg
            shEG/J0aIg6UgmxsTjWcHVR2BIuIW3uqBB27kRqut/OwGiqVSeasTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T23:25:57Z"
    mac: ENC[AES256_GCM,data:klykjeeScsDgw6zWGd4cWKx5JuIpchw/EaiAkXTtVPKFxYXnxTEEahhzhjslHT6iC122Dcx9MvVmQEQ4bQAAAfD1my9rYV4X3SiMi/03zFWd0GSd4KObrXAHpzAesye+yN2GnIpLKBHLBl7Z9IgCmTxs4E4qfeP3Xpxs26zcie0=,iv:ye681aKY3N0eDSvqnuv8DQ6wyWC1DHxzg9EmGwv40/I=,tag:ehbp0sB17qhdYAiajsJQ4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:gHtYOJymDtIlkGf82IPK5KsiK3ciNVZbAmuiRGlS4Vkp4I5FYpxriVPYUaVPzEUI6U+TJXvq9/R3Jw==,iv:rmiDGse++M8AgX94FCjDJcwO9AjtzdXsN5UrY48rx7s=,tag:86RU6kBUGgeU97sNEbZTMA==,type:comment]
#ENC[AES256_GCM,data:YjeR3eppS+g/H3va5TpBQhRjRoYUg2hSCyLSKjSX1k6II/ZcolxEV0UKnjgou/opG0iGkIEPwCtV,iv:9XVjn/SB7yOlz83IqYuMPobW4kmnMbNUtbARsdd/Kog=,tag:nd7KyV0xmkEffQM6gq7msA==,type:comment]
apiVersion: ENC[AES256_GCM,data:TxM=,iv:B607RWnQsmX6pYDMHaRUMhrbA7UV7lTuxPUqGURLeSA=,tag:9JBmpug57xz/J1dDLnMt2Q==,type:str]
kind: ENC[AES256_GCM,data:Ush1hn8n,iv:W9DKOIxDMjISok23s66GzMsi3gzMciWDxrixjXuK1r0=,tag:ccvFwtZVw1b++b4jL05GuA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LzqqlG/Z96MHgIYmDNClxJZ6xQ==,iv:KrliMKhNw0MLuUoGi0/tBcYr3bTRk+Jd68jU0KZwpr0=,tag:1RoZoZaiu3PlaSgY6yTkMw==,type:str]
    namespace: ENC[AES256_GCM,data:dbUzuBxaDn4=,iv:pQfu9dq3CAXjypDLTrEbkPNugjR8hUofpcy+9LJ+C3E=,tag:XIBIhyqZ9H+cQWV52eLKmw==,type:str]
type: ENC[AES256_GCM,data:6vMgl0KV,iv:xObCgORYXu0+JbrvhO6bUzHbY1Nm67PF2rDlp9gMv8I=,tag:GeRpZpSZm2NV6Y/W9TbrNw==,type:str]
stringData:
    grafana: ENC[AES256_GCM,data:KOiPg34Hf8a0X7ySLEpscTLbyrHi82B/NNnTEQvQIatSH5bLhsxNOaZeeoKv+jAuZynJtcDobAFbMEdzWd8=,iv:fUCv5xQJD86rFNYS+WEi5fZ4vM/VrF9avl6dhbVaxsk=,tag:OiPsvG8Sjtn5pwi0zgM6Lg==,type:str]
    argocd: ENC[AES256_GCM,data:Le287YfLdqcz1HCxOSqhMEvLGFfrXr6xNthBSKtbN0OflYHemrbdj0zIcsMrabR9lj9N0g2dfo4kIo4b2f3jHg==,iv:QjBRwHIw6ON2+FaGzjN3Um3AyWWyBYx3YckfLdv3E4k=,tag:sa44+n07496wk8v5pKWpLA==,type:str]
sops:
    age:
        - recipient: age1m58w3a52776phxqzeyztezx09u4z7964ug0skf2rvzrzw63v2dhq602hcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWXJRbGhvd0R4QktsQzNN
            TnM5WTJJaTBXTThJM3kzSGs5a2tBNHlBa1NBCmxXS3JzU2pPYk91WEJ3cVRpekZo
            UFBZMnRtaWJtZHVDMUxzQi9DdUh5WlUKLS0tIEJLZDFSNGxWdjFRNEtBN0paR1RT
            Mk9pOUdLd3dHa1drZXpEYkFQYlI0LzgK1Co3WrZ1trtwqBeGPytTbz7SkpviZKlg
            shEG/J0aIg6UgmxsTjWcHVR2BIuIW3uqBB27kRqut/OwGiqVSeasTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T23:25:57Z"
    mac: ENC[AES256_GCM,data:klykjeeScsDgw6zWGd4cWKx5JuIpchw/EaiAkXTtVPKFxYXnxTEEahhzhjslHT6iC122Dcx9MvVmQEQ4bQAAAfD1my9rYV4X3SiMi/03zFWd0GSd4KObrXAHpzAesye+yN2GnIpLKBHLBl7Z9IgCmTxs4E4qfeP3Xpxs26zcie0=,iv:ye681aKY3N0eDSvqnuv8DQ6wyWC1DHxzg9EmGwv40/I=,tag:ehbp0sB17qhdYAiajsJQ4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:3EPEoG7BlY95yhBpwk31Zl5p/JPlu6yqvWX4mnyifPltX1uAJfsVCBZq73sqc4cvuW9OQS0nfFn6,iv:2w1wsEFL+VuiDpq9XGGyS34yMwI14MwBoLbOcorzW9k=,tag:cRgfr8RMaWSYoeC0vudHrg==,type:comment]
apiVersion: ENC[AES256_GCM,data:pWA=,iv:cD4uupAZ6eSGYzZYdp7xUOXrY+WDD1PO7bqeWlbVcwY=,tag:l1/qFJ7GezZTxGL9WR69bw==,type:str]
kind: ENC[AES256_GCM,data:ybUFMKdD,iv:V1Upz7/XLqwJOQ+owRbpAhIe5vdghwybyso/n7wbYZk=,tag:kluSa7ZrLh74f9wy67XMwA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:t0JePigUlEORTtofwmDmA6yc/m0=,iv:0iA7KhhJ6wuyPE1LJjWY0K6GAUdWYJkjq5PINTeTMdo=,tag:uqN/e/3Tm62ykj25v17BtA==,type:str]
    namespace: ENC[AES256_GCM,data:L7w4JXPDgK8=,iv:ZzAoNqGJnMm5hL0twgA60rvz96U2eM+GNwx2YNtS8GI=,tag:3/f0+fH9C42VeJ3sxV5hgQ==,type:str]
type: ENC[AES256_GCM,data:zo1TLAru15fZgBsbTdmM0Pausgap00Mq,iv:fdyufLFhMaVZGDB5A89Jm6FHEKunh05vUZkAlPR4HFg=,tag:XbQAMjyOluh+LAUN6+ecAg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:FwNZA4V1P7k=,iv:Y8Rr3gxF3doX7TGS1sTw7xwEjZkvW5r7xpE6WheqL2o=,tag:kbBcu4SwPkeVmITnNIYVmA==,type:str]
    password: ENC[AES256_GCM,data:/jrOQ+3U7CD8cPlvdRtFqrJdaJsi1urUqkr6rd/j/jE=,iv:DjDku7sgiibEkD3KU4ukTUcWW+q4ytJK/c1MN+KBlgo=,tag:Xvgq+OWSjuKkKCJE2rEGDw==,type:str]
sops:
    age:
        - recipient: age1m58w3a52776phxqzeyztezx09u4z7964ug0skf2rvzrzw63v2dhq602hcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWXJRbGhvd0R4QktsQzNN
            TnM5WTJJaTBXTThJM3kzSGs5a2tBNHlBa1NBCmxXS3JzU2pPYk91WEJ3cVRpekZo
            UFBZMnRtaWJtZHVDMUxzQi9DdUh5WlUKLS0tIEJLZDFSNGxWdjFRNEtBN0paR1RT
            Mk9pOUdLd3dHa1drZXpEYkFQYlI0LzgK1Co3WrZ1trtwqBeGPytTbz7SkpviZKlg
            shEG/J0aIg6UgmxsTjWcHVR2BIuIW3uqBB27kRqut/OwGiqVSeasTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T23:25:57Z"
    mac: ENC[AES256_GCM,data:klykjeeScsDgw6zWGd4cWKx5JuIpchw/EaiAkXTtVPKFxYXnxTEEahhzhjslHT6iC122Dcx9MvVmQEQ4bQAAAfD1my9rYV4X3SiMi/03zFWd0GSd4KObrXAHpzAesye+yN2GnIpLKBHLBl7Z9IgCmTxs4E4qfeP3Xpxs26zcie0=,iv:ye681aKY3N0eDSvqnuv8DQ6wyWC1DHxzg9EmGwv40/I=,tag:ehbp0sB17qhdYAiajsJQ4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:VdJcQeMMWVde5Tr5SxSUbyPJvPA41I1qQfo=,iv:GiOCXWIJ3JB/sDglDgebbSu8NYrF+PEakpfRl5hKVDo=,tag:mRhx1aHVxnoHIIFBcpzNqw==,type:comment]
apiVersion: ENC[AES256_GCM,data:LrI=,iv:dDa+TLkqR8u1G9+vmsmyaRYYy8nx7q8Mfjhi1Zmv2pA=,tag:NLQQFjq86OkDOLZEETXRVA==,type:str]
kind: ENC[AES256_GCM,data:75I617sK,iv:JC7plaoXUEtKMhiJR7adit73R99DlXLsWW/mwiYd4kM=,tag:LON4B0rZP2gfgFbFaqpuSw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MZvE4kShs2c/UZ9AGQ==,iv:D7kjOiXWECTVcjcpyt4r9kljPOn5KirnOoMBBPRKTBk=,tag:0luh3uwRoG+rRgNPs+GYew==,type:str]
    namespace: ENC[AES256_GCM,data:KupQRyIHOBjMOg==,iv:EIrhmZYLmKOxyQwD+djoYq2zae4Nt+yEsLIvU4ZLtuw=,tag:w0Jo5kevA4n3FLm3z+qIbQ==,type:str]
type: ENC[AES256_GCM,data:FIDF1Wxw,iv:Di0BY4Vn/57Q2/dY+NO073XoF3aA8C6AaFufR+drelw=,tag:Os+4IeUMDI0K+QyamUaVrQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:8paF9b0=,iv:9cDxnvXGelCFFSjovmy7QivcLMBJR3rgCxJcMwixiqs=,tag:S5h0Qf2UjXaRzuYHpk8uyg==,type:str]
    admin-password: ENC[AES256_GCM,data:jvV0HDuabALXclHZHJQvWYkf/ljh9ALo0kztdvdmIdU=,iv:yPnF/7CbYofo7r1BF9UzVaXB3lI3+vN4Mzzub+R4lTE=,tag:vMV+IFXMcIz4i3PyFpv/ww==,type:str]
sops:
    age:
        - recipient: age1m58w3a52776phxqzeyztezx09u4z7964ug0skf2rvzrzw63v2dhq602hcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWXJRbGhvd0R4QktsQzNN
            TnM5WTJJaTBXTThJM3kzSGs5a2tBNHlBa1NBCmxXS3JzU2pPYk91WEJ3cVRpekZo
            UFBZMnRtaWJtZHVDMUxzQi9DdUh5WlUKLS0tIEJLZDFSNGxWdjFRNEtBN0paR1RT
            Mk9pOUdLd3dHa1drZXpEYkFQYlI0LzgK1Co3WrZ1trtwqBeGPytTbz7SkpviZKlg
            shEG/J0aIg6UgmxsTjWcHVR2BIuIW3uqBB27kRqut/OwGiqVSeasTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T23:25:57Z"
    mac: ENC[AES256_GCM,data:klykjeeScsDgw6zWGd4cWKx5JuIpchw/EaiAkXTtVPKFxYXnxTEEahhzhjslHT6iC122Dcx9MvVmQEQ4bQAAAfD1my9rYV4X3SiMi/03zFWd0GSd4KObrXAHpzAesye+yN2GnIpLKBHLBl7Z9IgCmTxs4E4qfeP3Xpxs26zcie0=,iv:ye681aKY3N0eDSvqnuv8DQ6wyWC1DHxzg9EmGwv40/I=,tag:ehbp0sB17qhdYAiajsJQ4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:psd1YLqoG33bI8VHFnqlK/q4X5YBBqs/e9gFHMQrbSYSDlhpwR9EFGUBqYonpFxKjFE=,iv:+jIfSNdZ51snztrxydLx3lOkE1OIIRP0uYBrZrabqhc=,tag:pA1ZG2n7TZZAUK5vThHMvQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:8ok=,iv:7YeEkzKCxioINVFNR5u1U0SslwL8r/ggqvYu3eNmT7c=,tag:hscoLMaZ6ZGsfFV/wKEsrg==,type:str]
kind: ENC[AES256_GCM,data:x53WFJoN,iv:w3dXfoq1G71Z6spHv7d2GO/U8n9KEIf2l6G/LoWc3oo=,tag:0KMt2jFfhCEphwd/FigRbw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mVeEVE3saMlSmSg4HA==,iv:TQvOtgUarKc9MJIXqkketkou23E7G3VTBfNby62C22I=,tag:S60+UfEI/Bbu19+Ss3Knfg==,type:str]
    namespace: ENC[AES256_GCM,data:PN4kKCw3UwIkSg==,iv:O4CJdI6bFqBXLwv0MgdWPuO+WcCC07NJ/JfgMf5KCzA=,tag:cWtQI5N7g7iws5TIO0YSZw==,type:str]
type: ENC[AES256_GCM,data:vc6NUgPT,iv:O1/eaQzF+uhyidHc4dQVndMs8185HsQOedC4LKv49Ko=,tag:W8It9FkDvEzASlz3Gy+YhQ==,type:str]
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:2O7yM4LUvMLQqbytgk3UfajsjIGQpdC10bIF9sA6AdplNwr5hByR89PwEI3cGhT6F5XM41DNhRhrMMFnUvc=,iv:221dnNV8pNlPF8yVthYTvMmWTBYzyHU9x825+xHQAdk=,tag:hMQyudVgApE6nu6EiWx/sQ==,type:str]
sops:
    age:
        - recipient: age1m58w3a52776phxqzeyztezx09u4z7964ug0skf2rvzrzw63v2dhq602hcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWXJRbGhvd0R4QktsQzNN
            TnM5WTJJaTBXTThJM3kzSGs5a2tBNHlBa1NBCmxXS3JzU2pPYk91WEJ3cVRpekZo
            UFBZMnRtaWJtZHVDMUxzQi9DdUh5WlUKLS0tIEJLZDFSNGxWdjFRNEtBN0paR1RT
            Mk9pOUdLd3dHa1drZXpEYkFQYlI0LzgK1Co3WrZ1trtwqBeGPytTbz7SkpviZKlg
            shEG/J0aIg6UgmxsTjWcHVR2BIuIW3uqBB27kRqut/OwGiqVSeasTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T23:25:57Z"
    mac: ENC[AES256_GCM,data:klykjeeScsDgw6zWGd4cWKx5JuIpchw/EaiAkXTtVPKFxYXnxTEEahhzhjslHT6iC122Dcx9MvVmQEQ4bQAAAfD1my9rYV4X3SiMi/03zFWd0GSd4KObrXAHpzAesye+yN2GnIpLKBHLBl7Z9IgCmTxs4E4qfeP3Xpxs26zcie0=,iv:ye681aKY3N0eDSvqnuv8DQ6wyWC1DHxzg9EmGwv40/I=,tag:ehbp0sB17qhdYAiajsJQ4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:PY5sn0Fe/fXTUXzIAaYqMAEyrZ/jn4uccobTKVin2kyaDcehb+hYGCKlD2Tisyw38kJTVaxB,iv:k1ytHOAp4fPaQVPAlNN/JwZ1ASSi/8MCYQFVBGzqA04=,tag:GGH8nt42hsNdR0kjUOPElg==,type:comment]
#ENC[AES256_GCM,data:pzgjg4GYrrrp4ncksoVsE9FwPMbDnInrWpRNLTDYQg1oWYdBXcA4X9GcAqCS8OKxODQ6VEY=,iv:BAVgBw79DxJSniu2kYB84PWk1J/Hufxr6p47hnb3C3g=,tag:u1zKhTm5assAeGYzmzI2XQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:08A=,iv:u9arHybMVESG5fRwiNtHUUyz6Nr3Sn/XKb/9qyncjzU=,tag:rLRWjXbtTvNdkJftDr7axg==,type:str]
kind: ENC[AES256_GCM,data:cMZvuZpM,iv:fPeaKxAiTbcsmsdAureE6IXmXEZT07wgVOdX0TG/yg4=,tag:c5Vp7HaGTVPbR5g6S9y80Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UXm+ftnf2JWrtFzTQw==,iv:2Gjxb6FxvwO3hfAt87pAmdg/9ufF1qGw3COYRFrzek0=,tag:5qaBLSz9rvdPVFHp/rFFTQ==,type:str]
    namespace: ENC[AES256_GCM,data:dr+i8gID,iv:X67R15qNmIbgbKoqyOQ7OFw2GmDgoRjXRAl+7Su8MIk=,tag:LTym1bkqa4SMK+AMpuy28g==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:V4fCwJp1ha99wNtENw==,iv:oFnVUVLwLy2cxkHWWqgl/g9AuPfsmmN+vmkzq7caeB4=,tag:k/VRBmmixXPzb61BIacM7w==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:acpWRVWC,iv:jETcrZHJYjeYTexzYJF3wDU/YU1DsrC/o+E8uexdTec=,tag:Ec9fH0vM5WWKoed+xqnOmw==,type:str]
type: ENC[AES256_GCM,data:I5z8nMIb,iv:pVv4nm2qiLksGXCQYo2NcFBr/NtKd3fR+DbQrNh9cqM=,tag:WUOfk2IoaK1k9Sld5iVtzw==,type:str]
stringData:
    #ENC[AES256_GCM,data:YVptBmRIiQZh4a2BDQ1Xm74LRpIQywSo6pWxAXoYS5omwWuHRqrBzkZRn4cor0FTNrQdkBcqAAMrE/aMHMsyaLY1ExbqT3mqf2OgfbObmYorbT9nGBkg8F+Oqg==,iv:7bWOGfBPyMQgsfFatvz93NGTI0t8Oqk9ineaIP4q8/8=,tag:ctu0U/PpZykAzxSXASAq6A==,type:comment]
    oidc.keycloak.clientSecret: ENC[AES256_GCM,data:UPj65SaS3tdGhEXeT8sCSW0W0I3B9Afn4jlA/U9sm/DfbZhSNiAmS43qN86G8r6QutP9pZOdf86fP2bT84h+Ag==,iv:yAvum1gCYi2iRVd2KGO5rom/ikrn0KoyfNmwxC8b778=,tag:5XDGPUi6Ioa/DLDPe4py9Q==,type:str]
sops:
    age:
        - recipient: age1m58w3a52776phxqzeyztezx09u4z7964ug0skf2rvzrzw63v2dhq602hcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWXJRbGhvd0R4QktsQzNN
            TnM5WTJJaTBXTThJM3kzSGs5a2tBNHlBa1NBCmxXS3JzU2pPYk91WEJ3cVRpekZo
            UFBZMnRtaWJtZHVDMUxzQi9DdUh5WlUKLS0tIEJLZDFSNGxWdjFRNEtBN0paR1RT
            Mk9pOUdLd3dHa1drZXpEYkFQYlI0LzgK1Co3WrZ1trtwqBeGPytTbz7SkpviZKlg
            shEG/J0aIg6UgmxsTjWcHVR2BIuIW3uqBB27kRqut/OwGiqVSeasTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T23:25:57Z"
    mac: ENC[AES256_GCM,data:klykjeeScsDgw6zWGd4cWKx5JuIpchw/EaiAkXTtVPKFxYXnxTEEahhzhjslHT6iC122Dcx9MvVmQEQ4bQAAAfD1my9rYV4X3SiMi/03zFWd0GSd4KObrXAHpzAesye+yN2GnIpLKBHLBl7Z9IgCmTxs4E4qfeP3Xpxs26zcie0=,iv:ye681aKY3N0eDSvqnuv8DQ6wyWC1DHxzg9EmGwv40/I=,tag:ehbp0sB17qhdYAiajsJQ4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
#ENC[AES256_GCM,data:Hx3J4Yu+2Wj4BlD0I+11OEON7ouSae7VyX0PEWyitwJJQWbjcFIr/OatILJOIzo=,iv:A6HEH4u0UDmNErr5EAW2LYbxW+P4h/29SKCZK6WX7rw=,tag:usZkWQN59kum9FR4Oz9DIw==,type:comment]
apiVersion: ENC[AES256_GCM,data:kf4=,iv:V5O5C/ha2W6gFWTYCVzUOkKQFvaqNvMjRLkb6tPLkUs=,tag:UJzGNp6+0zzWTJZlK4JS7Q==,type:str]
kind: ENC[AES256_GCM,data:apD7npu5,iv:KLi8zqON48TPVnLiI6BGrVYGjMt1OqzRFTPhPKH/7CM=,tag:ymNDI/5vQFiGtwT42CPbxA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qHbPpFBcGwLWRLt2,iv:Rpf8FzW1mhY9bxks5PEwOFgPgLkAzFLye4ffERtlflQ=,tag:sGJyyRKbFCwn5v9F06APCg==,type:str]
    namespace: ENC[AES256_GCM,data:0/LSghhT,iv:R/TxTq5LB6mAP42WAlH4f9kQTO7lp1e1n5WIx/OwlMk=,tag:0INqh2Sy5bqgDCu0skf31w==,type:str]
type: ENC[AES256_GCM,data:Ca8Uwx3U,iv:zE9B8jYqVoW18oxlJvO6fGyDNRSrGZnCjiY78sLmjAg=,tag:+0xVSNGBemoYd9MshkofkA==,type:str]
stringData:
    keys.txt: ENC[AES256_GCM,data:7zhMwyiUO/3+9Tmp1b7zsZ+cLXKnFOISAh20HB4EUoiqBXuIdUn96mHOi/JBYtU/LYCPptMD8R3wRHbg1HjO7kuvxD6DzWTQWSks,iv:bJfxFPAJaPII8UpXvOUUT1O2hpa6j6+h1cgVfTD29Gc=,tag:GyXyeeRuM4knwuqMbFF5ZA==,type:str]
sops:
    age:
        - recipient: age1m58w3a52776phxqzeyztezx09u4z7964ug0skf2rvzrzw63v2dhq602hcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWXJRbGhvd0R4QktsQzNN
            TnM5WTJJaTBXTThJM3kzSGs5a2tBNHlBa1NBCmxXS3JzU2pPYk91WEJ3cVRpekZo
            UFBZMnRtaWJtZHVDMUxzQi9DdUh5WlUKLS0tIEJLZDFSNGxWdjFRNEtBN0paR1RT
            Mk9pOUdLd3dHa1drZXpEYkFQYlI0LzgK1Co3WrZ1trtwqBeGPytTbz7SkpviZKlg
            shEG/J0aIg6UgmxsTjWcHVR2BIuIW3uqBB27kRqut/OwGiqVSeasTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T23:25:57Z"
    mac: ENC[AES256_GCM,data:klykjeeScsDgw6zWGd4cWKx5JuIpchw/EaiAkXTtVPKFxYXnxTEEahhzhjslHT6iC122Dcx9MvVmQEQ4bQAAAfD1my9rYV4X3SiMi/03zFWd0GSd4KObrXAHpzAesye+yN2GnIpLKBHLBl7Z9IgCmTxs4E4qfeP3Xpxs26zcie0=,iv:ye681aKY3N0eDSvqnuv8DQ6wyWC1DHxzg9EmGwv40/I=,tag:ehbp0sB17qhdYAiajsJQ4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
