apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: linkwarden
    repo: https://charts.schoenwald.aero
    version: 1.0.14
    releaseName: linkwarden
    namespace: linkwarden
    valuesInline:
      image:
        tag: "v2.15.1"
      persistence:
        enabled: false
        size: 100Mi
      env:
        nextauth:
          ## @param env.nextauth.url Defines the NEXTAUTH_URL and specifies the base URL for NextAuth.js authentication endpoints.
          ## @param env.nextauth.secret Defines the NEXTAUTH_SECRET and is used by NextAuth.js to encrypt session tokens and JWTs. Can be generatet via `openssl rand -base64 32`
          existingSecret:
            ## @param env.nextauth.existingSecret.name Defines the NEXTAUTH_SECRET kubernetes secret name where to get the secret.
            name: "linkwarden"
            ## @param env.nextauth.existingSecret.key Defines the NEXTAUTH_SECRET kubernetes secret key where to get the secret.
            key: "nextjs-auth"
      extraEnv:
        - name: NEXT_PUBLIC_DISABLE_REGISTRATION
          value: "true"
        - name: NEXT_PUBLIC_CREDENTIALS_ENABLED
          value: "true"
        - name: DISABLE_NEW_SSO_USERS
          value: "true"
        - name: NEXT_PUBLIC_EMAIL_PROVIDER
          value: "true"
        - name: EMAIL_FROM
          value: "noreply@linkwarden"
        - name: MAX_WORKERS
          value: "1"
        - name: MALLOC_ARENA_MAX
          value: "2"
        - name: NODE_OPTIONS
          value: "--max-old-space-size=400"
        - name: ARCHIVE_TAKE_COUNT
          value: "1"
        - name: RSS_SUBSCRIPTION_LIMIT_PER_USER
          value: "150"
        - name: NEXT_PUBLIC_RSS_POLLING_INTERVAL_MINUTES
          value: "720"
      externalPostgresql:
        host: postgresql
        existingSecret:
          ## @param env.nextauth.existingSecret.name Defines the NEXTAUTH_SECRET kubernetes secret name where to get the secret.
          name: "linkwarden"
          ## @param env.nextauth.existingSecret.key Defines the NEXTAUTH_SECRET kubernetes secret key where to get the secret.
          keys:
            username: "postgres-user"
            password: "postgres-passwd"
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          memory: 2Gi
resources:
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - hpa.yaml

patches:
  - target:
      kind: Deployment
      name: linkwarden
    path: linkwarden-custom.yaml
  - target:
      kind: Deployment
      name: linkwarden
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/name
        value: linkwarden
      - op: test
        path: /spec/template/spec/containers/0/env/8/name
        value: DATABASE_URL
      - op: replace
        path: /spec/template/spec/containers/0/env/8/value
        value: "postgresql://$(LINKWARDEN_POSTGRES_USER):$(LINKWARDEN_POSTGRES_PASSWORD)@$(LINKWARDEN_POSTGRES_HOST):$(LINKWARDEN_POSTGRES_PORT)/$(LINKWARDEN_POSTGRES_DATABASE)"
