# Landing page - static website for etcd.me root domain
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    # Image updater: auto-update when new images are pushed
    argocd-image-updater.argoproj.io/image-list: landing=ghcr.io/sofianedjerbi/homelanding:latest
    argocd-image-updater.argoproj.io/landing.update-strategy: digest
spec:
  project: landing
  source:
    repoURL: https://github.com/sofianedjerbi/homelanding
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: landing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
