# n8n workflow automation - etcd.me overlay
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: 1.16.8
    helm:
      valuesObject:
        # Disable embedded PostgreSQL
        postgresql:
          enabled: false
        # Use PostgreSQL database type
        db:
          type: postgresdb
        # External PostgreSQL configuration
        externalPostgresql:
          host: postgres-rw.postgres.svc.cluster.local
          port: 5432
          database: n8n
          username: n8n
          existingSecret: n8n-postgres
        # Encryption key from secret
        existingEncryptionKeySecret: n8n-encryption
        # Timezone
        timezone: Europe/Paris
        # Main container config - SSO via oauth2-proxy
        main:
          extraEnvVars:
            # External hooks file for SSO authentication
            EXTERNAL_HOOK_FILES: "/hooks/hooks.js"
            # Header set by oauth2-proxy containing authenticated user email
            N8N_FORWARD_AUTH_HEADER: "X-Forwarded-Email"
            # Keycloak logout URL for full SSO logout chain
            N8N_KEYCLOAK_LOGOUT_URL: "https://auth.etcd.me/realms/homelab/protocol/openid-connect/logout?post_logout_redirect_uri=https://n8n.etcd.me&client_id=n8n"
          volumes:
            - name: hooks
              configMap:
                name: n8n-hooks
          volumeMounts:
            - name: hooks
              mountPath: /hooks
              readOnly: true
        # Ingress disabled (using gateway)
        ingress:
          enabled: false
        # Service config
        service:
          enabled: true
          type: ClusterIP
          port: 5678
        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        # Probe configuration - give n8n more time to start
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 30
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
