# n8n MCP Server - Workflow building assistant for LLMs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-mcp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: REPO_URL_PLACEHOLDER
    targetRevision: HEAD
    path: argocd/base/resources/n8n-mcp
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
