repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 9.1.3
    createNamespace: true
    wait: true
    values:
      - configs:
          secret:
            createSecret: false
