# Job to sync n8n client secret to Keycloak after realm import
# Runs after KeycloakRealmImport (sync-wave 4)
# Must run in keycloak namespace to access keycloak-initial-admin secret
apiVersion: batch/v1
kind: Job
metadata:
  name: n8n-keycloak-secret-sync
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sync-secret
          image: curlimages/curl:8.5.0
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          env:
            - name: KEYCLOAK_URL
              value: "http://keycloak-service.keycloak.svc.cluster.local:8080"
            - name: REALM
              value: "homelab"
            - name: CLIENT_ID
              value: "n8n"
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-admin
                  key: username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-admin
                  key: password
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: n8n-client-secret
                  key: client-secret
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Getting admin token..."
              TOKEN=$(curl -s -X POST "${KEYCLOAK_URL}/realms/master/protocol/openid-connect/token" \
                -H "Content-Type: application/x-www-form-urlencoded" \
                -d "username=${ADMIN_USER}" \
                -d "password=${ADMIN_PASSWORD}" \
                -d "grant_type=password" \
                -d "client_id=admin-cli" | sed 's/.*"access_token":"\([^"]*\)".*/\1/')

              if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
                echo "Failed to get admin token"
                exit 1
              fi
              echo "Got admin token"

              echo "Getting client UUID..."
              CLIENT_UUID=$(curl -s -X GET "${KEYCLOAK_URL}/admin/realms/${REALM}/clients?clientId=${CLIENT_ID}" \
                -H "Authorization: Bearer ${TOKEN}" | sed 's/.*"id":"\([^"]*\)".*/\1/')

              if [ -z "$CLIENT_UUID" ] || [ "$CLIENT_UUID" = "null" ]; then
                echo "Failed to get client UUID"
                exit 1
              fi
              echo "Got client UUID: ${CLIENT_UUID}"

              echo "Updating client secret..."
              curl -s -X PUT "${KEYCLOAK_URL}/admin/realms/${REALM}/clients/${CLIENT_UUID}" \
                -H "Authorization: Bearer ${TOKEN}" \
                -H "Content-Type: application/json" \
                -d "{\"clientId\": \"${CLIENT_ID}\", \"secret\": \"${CLIENT_SECRET}\"}"

              echo "Client secret updated successfully"
