apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - recovery-storage-class.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - recurring-job.yaml
configMapGenerator:
  - name: uptime-kuma-maintenance
    namespace: uptime-kuma
    files:
      - maintenance.sh
generatorOptions:
  disableNameSuffixHash: true
