apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: uptime-kuma-cleanup-trim
  namespace: longhorn-system
spec:
  cron: "10 5 * * *"
  task: filesystem-trim
  groups:
    - uptime-kuma-cleanup
  retain: 0
  concurrency: 1
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: c-s2q8hy
  namespace: longhorn-system
spec:
  cron: "5 5 * * *"
  task: backup
  groups: []
  retain: 1
  concurrency: 1
  labels:
    app: uptime-kuma
