apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sftpgo
  namespace: argocd
spec:
  project: default
  source:
    chart: sftpgo
    repoURL: https://charts.sagikazarmark.dev
    targetRevision: 0.23.2
    helm:
      valuesObject:
        ftpd.enabled: true
        volumes:
          - name: qbittorrent-downloads
            persistentVolumeClaim:
              claimName: media-qbittorrent-downloads
        volumeMounts:
          - name: media-qbittorrent-downloads
            mountPath: /data


  destination:
    server: "https://kubernetes.default.svc"
    namespace: media
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
