# Uptime Kuma - self-hosted monitoring tool
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://dirsigler.github.io/uptime-kuma-helm
    chart: uptime-kuma
    targetRevision: 2.24.0
    helm:
      valuesObject:
        # Deployment instead of StatefulSet
        useDeploy: true
        # Service configuration
        service:
          type: ClusterIP
          port: 3001
        # Ingress disabled (using gateway)
        ingress:
          enabled: false
        # Persistence for monitoring data
        volume:
          enabled: true
          accessMode: ReadWriteOnce
          size: 4Gi
        # Resources
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
