apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: Filebrowser
    repoURL: http://brandan-schmitz.github.io/helm-charts
    targetRevision: 1.2.0
    helm:
      valuesObject:
        persistence:
          data:
            enabled: false
            existingClaim: "media-qbittorrent-downloads"

  destination:
    server: https://kubernetes.default.svc
    namespace: media  # Ajuste selon ton namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
