# n8n workflow automation
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: 1.16.8
    helm:
      valuesObject:
        # Disable embedded PostgreSQL
        postgresql:
          enabled: false
        # External PostgreSQL configuration
        externalPostgresql:
          host: postgres-rw.postgres.svc.cluster.local
          port: 5432
          database: n8n
          username: n8n
          existingSecret: n8n-postgres
        # Encryption key from secret
        existingEncryptionKeySecret: n8n-encryption
        # Timezone
        timezone: Europe/Paris
        # Executions settings
        config:
          executions:
            pruneData: "true"
            pruneDataMaxAge: 168
        # Ingress disabled (using gateway)
        ingress:
          enabled: false
        # Service config
        service:
          enabled: true
          type: ClusterIP
          port: 5678
        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
